// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthChecker creates a new instance of MockHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthChecker {
	mock := &MockHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthChecker is an autogenerated mock type for the HealthChecker type
type MockHealthChecker struct {
	mock.Mock
}

type MockHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthChecker) EXPECT() *MockHealthChecker_Expecter {
	return &MockHealthChecker_Expecter{mock: &_m.Mock}
}

// IsBlueButtonOK provides a mock function for the type MockHealthChecker
func (_mock *MockHealthChecker) IsBlueButtonOK() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBlueButtonOK")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHealthChecker_IsBlueButtonOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlueButtonOK'
type MockHealthChecker_IsBlueButtonOK_Call struct {
	*mock.Call
}

// IsBlueButtonOK is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) IsBlueButtonOK() *MockHealthChecker_IsBlueButtonOK_Call {
	return &MockHealthChecker_IsBlueButtonOK_Call{Call: _e.mock.On("IsBlueButtonOK")}
}

func (_c *MockHealthChecker_IsBlueButtonOK_Call) Run(run func()) *MockHealthChecker_IsBlueButtonOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_IsBlueButtonOK_Call) Return(b bool) *MockHealthChecker_IsBlueButtonOK_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHealthChecker_IsBlueButtonOK_Call) RunAndReturn(run func() bool) *MockHealthChecker_IsBlueButtonOK_Call {
	_c.Call.Return(run)
	return _c
}

// IsDatabaseOK provides a mock function for the type MockHealthChecker
func (_mock *MockHealthChecker) IsDatabaseOK() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDatabaseOK")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthChecker_IsDatabaseOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDatabaseOK'
type MockHealthChecker_IsDatabaseOK_Call struct {
	*mock.Call
}

// IsDatabaseOK is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) IsDatabaseOK() *MockHealthChecker_IsDatabaseOK_Call {
	return &MockHealthChecker_IsDatabaseOK_Call{Call: _e.mock.On("IsDatabaseOK")}
}

func (_c *MockHealthChecker_IsDatabaseOK_Call) Run(run func()) *MockHealthChecker_IsDatabaseOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_IsDatabaseOK_Call) Return(s string, b bool) *MockHealthChecker_IsDatabaseOK_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockHealthChecker_IsDatabaseOK_Call) RunAndReturn(run func() (string, bool)) *MockHealthChecker_IsDatabaseOK_Call {
	_c.Call.Return(run)
	return _c
}

// IsSsasIntrospectOK provides a mock function for the type MockHealthChecker
func (_mock *MockHealthChecker) IsSsasIntrospectOK() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSsasIntrospectOK")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthChecker_IsSsasIntrospectOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSsasIntrospectOK'
type MockHealthChecker_IsSsasIntrospectOK_Call struct {
	*mock.Call
}

// IsSsasIntrospectOK is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) IsSsasIntrospectOK() *MockHealthChecker_IsSsasIntrospectOK_Call {
	return &MockHealthChecker_IsSsasIntrospectOK_Call{Call: _e.mock.On("IsSsasIntrospectOK")}
}

func (_c *MockHealthChecker_IsSsasIntrospectOK_Call) Run(run func()) *MockHealthChecker_IsSsasIntrospectOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_IsSsasIntrospectOK_Call) Return(s string, b bool) *MockHealthChecker_IsSsasIntrospectOK_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockHealthChecker_IsSsasIntrospectOK_Call) RunAndReturn(run func() (string, bool)) *MockHealthChecker_IsSsasIntrospectOK_Call {
	_c.Call.Return(run)
	return _c
}

// IsSsasOK provides a mock function for the type MockHealthChecker
func (_mock *MockHealthChecker) IsSsasOK() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSsasOK")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthChecker_IsSsasOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSsasOK'
type MockHealthChecker_IsSsasOK_Call struct {
	*mock.Call
}

// IsSsasOK is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) IsSsasOK() *MockHealthChecker_IsSsasOK_Call {
	return &MockHealthChecker_IsSsasOK_Call{Call: _e.mock.On("IsSsasOK")}
}

func (_c *MockHealthChecker_IsSsasOK_Call) Run(run func()) *MockHealthChecker_IsSsasOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_IsSsasOK_Call) Return(s string, b bool) *MockHealthChecker_IsSsasOK_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockHealthChecker_IsSsasOK_Call) RunAndReturn(run func() (string, bool)) *MockHealthChecker_IsSsasOK_Call {
	_c.Call.Return(run)
	return _c
}

// IsWorkerDatabaseOK provides a mock function for the type MockHealthChecker
func (_mock *MockHealthChecker) IsWorkerDatabaseOK() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWorkerDatabaseOK")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthChecker_IsWorkerDatabaseOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWorkerDatabaseOK'
type MockHealthChecker_IsWorkerDatabaseOK_Call struct {
	*mock.Call
}

// IsWorkerDatabaseOK is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) IsWorkerDatabaseOK() *MockHealthChecker_IsWorkerDatabaseOK_Call {
	return &MockHealthChecker_IsWorkerDatabaseOK_Call{Call: _e.mock.On("IsWorkerDatabaseOK")}
}

func (_c *MockHealthChecker_IsWorkerDatabaseOK_Call) Run(run func()) *MockHealthChecker_IsWorkerDatabaseOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_IsWorkerDatabaseOK_Call) Return(s string, b bool) *MockHealthChecker_IsWorkerDatabaseOK_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockHealthChecker_IsWorkerDatabaseOK_Call) RunAndReturn(run func() (string, bool)) *MockHealthChecker_IsWorkerDatabaseOK_Call {
	_c.Call.Return(run)
	return _c
}
