scaling:
  min: 2
  max: 4

ecs:
  cpu: 256
  mem: 512

ports:
  admin_port: 444
  https_port: 443
  ssas_public_port: 3003
  ssas_admin_port: 3004

health_check:
  path: "/_health"
  idle_timeout: 60
  interval: 15
  healthy_threshold: 2
  unhealthy_threshold: 5
  timeout: 5
  start_period: 10

ssl_policy: "ELBSecurityPolicy-TLS13-1-2-Res-2021-06"

parameter_names: [
    "BCDA_TLS_CERT",
    "BCDA_TLS_KEY",
    "CONFIG_BUCKET",
    "DATABASE_URL",
    "DEBUG",
    "DEPLOYMENT_TARGET",
    "GOPATH",
    "SSAS_ADMIN_SIGNING_KEY_PATH",
    "SSAS_CLIENT_ASSERTION_AUD",
    "SSAS_CRED_EXPIRATION_DAYS",
    "SSAS_DEFAULT_SYSTEM_SCOPE",
    "SSAS_HASH_ITERATIONS",
    "SSAS_HASH_KEY_LENGTH",
    "SSAS_HASH_SALT_SIZE",
    "SSAS_IDLE_TIMEOUT",
    "SSAS_LOG",
    "SSAS_MFA_TOKEN_TIMEOUT_MINUTES",
    "SSAS_PUBLIC_SIGNING_KEY_PATH",
    "SSAS_PUBLIC_URL",
    "SSAS_RATE_LIMIT_DURATION_MINUTES",
    "SSAS_RATE_LIMIT_THRESHOLD",
    "SSAS_READ_TIMEOUT",
    "SSAS_TOKEN_DENYLIST_CACHE_CLEANUP_MINUTES",
    "SSAS_TOKEN_DENYLIST_CACHE_TIMEOUT_MINUTES",
    "SSAS_WRITE_TIMEOUT"
  ]
