aco_config:
    # Kidney Care Choices (KCC) Model - Comprehensive Kidney Care Contracting
    - model: "CKCC" # Active, managed by 4i
      name_pattern: "C\\d{4}"
      performance_year_transition: "01/01"
      lookback_period: 2
      data:
        - "adjudicated"
    # Kidney Care Choices (KCC) Model - Kidney Care First
    - model: "KCF" # Ended, managed by 4i
      name_pattern: "K\\d{4}"
      performance_year_transition: "01/01"
      lookback_period: 2
      data:
        - "adjudicated"
    # ACO REACH Model, formerly Global and Professional Direct Contracting Model (GPDC) Model
    - model: "DC" # Active, managed by 4i
      name_pattern: "D\\d{4}"
      performance_year_transition: "04/01"
      lookback_period: 3
      data:
        - "partially-adjudicated"
        - "adjudicated"
    # Medicare Shared Savings Program
    - model: "SSP" # Active, managed by ACO-MS
      name_pattern: "^A\\d{4}"
      data:
        - "adjudicated"
    # Comprehensive ESRD Care (CEC) Model
    - model: "CEC" # Ended
      name_pattern: "E\\d{4}"
      data:
        - "adjudicated"
    # Next Generation ACO Model
    - model: "NGACO" # Ended
      name_pattern: "V\\d{3}"
      data:
        - "adjudicated"
    # A config for BCDA's test entities
    - model: "TEST" # Active, managed by BCDA Admin
      name_pattern: "TEST\\d{3}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
    # Maryland Total Cost of Care (MD TCoC) Model
    - model: "TCOCMD" # Active, managed by BCDA Admin
      name_pattern: "CT\\d{6}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(PCPB)\.(M)([0-9][0-9])(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "PCPB"
        file_performance_year: 4
        file_date: 6
        metadata_matches: 7
      ignore_suppressions: true
    # CMS Data Aggregation Contract
    - model: "CDAC" # Active, managed by IHP
      name_pattern: "DA\\d{4}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(BCD)\.(DA\d{4}).(MBIY)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "BCD"
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
    # GUIDE (Guiding an Improved Dementia Experience) Model
    - model: "GUIDE" # Pending, managed by IHP
      name_pattern: "GUIDE-\\d{5}"
      data:
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(GUIDE)\.(GUIDE-)(\d{5})\.(Y)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "GUIDE"
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
    # Increasing Organ Transplant Access (IOTA) Model
    - model: "IOTA" # Pending, managed via 4i
      name_pattern: "IOTA\\d{3}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
rate_limit_config:
  all: true
  acos: []
v3_enabled_acos:
  - "TEST994"
v1_v2_deny_regexes: ["IOTA\\d{3}"]
v3_no_partial_claims_models:
  - "CKCC"
