aco_config:
    # Kidney Care Choices (KCC) Model - Comprehensive Kidney Care Contracting
    - model: 'CKCC' # Active, managed by 4i
      name_pattern: '^C\d{4}$'
      performance_year_transition: '01/01'
      lookback_period: 2
      data:
        - 'adjudicated'
    # Kidney Care Choices (KCC) Model - Kidney Care First
    - model: 'KCF' # Ended, managed by 4i
      name_pattern: '^K\d{4}$'
      performance_year_transition: '01/01'
      lookback_period: 2
      data:
        - 'adjudicated'
    # ACO REACH Model, formerly Global and Professional Direct Contracting Model (GPDC) Model
    - model: 'DC' # Active, managed by 4i
      name_pattern: '^D\d{4}$'
      performance_year_transition: '04/01'
      lookback_period: 3
      data:
        - 'partially-adjudicated'
        - 'adjudicated'
    # Medicare Shared Savings Program
    - model: 'SSP' # Active, managed by ACO-MS
      name_pattern: '^A\d{4}$'
      data:
        - 'adjudicated'
    # Comprehensive ESRD Care (CEC) Model
    - model: 'CEC' # Ended
      name_pattern: '^E\d{4}$'
      data:
        - 'adjudicated'
    # Next Generation ACO Model
    - model: 'NGACO' # Ended
      name_pattern: '^V\d{3}$'
      data:
        - 'adjudicated'
    # A config for BCDA's test entities
    - model: 'TEST' # Active, managed by BCDA Admin
      name_pattern: '^TEST\d{3}$'
      data:
        - 'adjudicated'
        - 'partially-adjudicated'
    # Maryland Total Cost of Care (MD TCoC) Model
    - model: 'TCOCMD' # Active, managed by BCDA Admin
      name_pattern: '^CT\d{4,6}$'
      data:
        - 'adjudicated'
        - 'partially-adjudicated'
      attribution_file:
        file_type: 'csv'
        name_pattern: '(P|T)\.(PCPB)\.(M)([0-9][0-9])(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: 'PCPB'
        file_performance_year: 4
        file_date: 6
        metadata_matches: 7
      ignore_suppressions: true
    # CMS Data Aggregation Contract
    - model: 'CDAC' # Active, managed by IHP
      name_pattern: '^DA\d{4}$'
      data:
        - 'adjudicated'
        - 'partially-adjudicated'
      attribution_file:
        file_type: 'csv'
        name_pattern: '(P|T)\.(BCD)\.(DA\d{4}).(MBIY)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: 'BCD'
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
    # GUIDE (Guiding an Improved Dementia Experience) Model
    - model: 'GUIDE' # Pending, managed by IHP
      name_pattern: '^GUIDE-\d{4}$'
      data:
        - 'adjudicated'
      attribution_file:
        file_type: 'csv'
        name_pattern: '(P|T)\.(GUIDE)\.(GUIDE-)(\d{4})\.(Y)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: 'GUIDE'
        file_performance_year: 6
        file_date: 7
        metadata_matches: 8
    # ACCESS (Advancing Chronic Care with Effective, Scalable Solutions) Model
    - model: 'ACCESS'
      name_pattern: '^ACCES\d{5}$' # only one 's' due to character limits
      lookback_period: 3
      data:
        - 'adjudicated'
      attribution_file:
        file_type: 'csv'
        name_pattern: '(P|T)\.(ACCESS)\.(ACCES\d{5})\.(Y)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: 'ACCESS'
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
    # Increasing Organ Transplant Access (IOTA) Model
    - model: 'IOTA' # Pending, managed via 4i
      name_pattern: '^IOTA\d{3}$'
      data:
        - 'adjudicated'
        - 'partially-adjudicated'
rate_limit_config:
  all: true
  acos: []
v3_enabled_acos:
  - 'A1001'
  - 'A1001'
  - 'A1199'
  - 'A1215'
  - 'A1702'
  - 'A1702'
  - 'A2833'
  - 'A3280'
  - 'A3280'
  - 'A3317'
  - 'A3317'
  - 'A3507'
  - 'A3507'
  - 'A3578'
  - 'A3578'
  - 'A4604'
  - 'A4604'
  - 'A4692'
  - 'A4692'
  - 'A4794'
  - 'A4974'
  - 'A4974'
  - 'A5049'
  - 'A5160'
  - 'A5160'
  - 'A5388'
  - 'A5388'
  - 'A5407'
  - 'A5407'
  - 'A5453'
  - 'A5453'
  - 'A5483'
  - 'A5483'
  - 'A5513'
  - 'A5513'
  - 'A5518'
  - 'A5518'
  - 'A5542'
  - 'A5542'
  - 'A5554'
  - 'A5554'
  - 'A5557'
  - 'A5557'
  - 'A5599'
  - 'A5599'
  - 'A5600'
  - 'A5600'
  - 'A5611'
  - 'A5611'
  - 'A5645'
  - 'A5645'
  - 'A5646'
  - 'A5646'
  - 'A5666'
  - 'A5666'
  - 'A5742'
  - 'A5742'
  - 'A5816'
  - 'A5816'
  - 'A5861'
  - 'A5861'
  - 'A5894'
  - 'A5894'
  - 'A5895'
  - 'A5895'
  - 'A5897'
  - 'A5897'
  - 'A5906'
  - 'A5906'
  - 'ACCES00136'
  - 'ACCES00267'
  - 'ACCES00317'
  - 'ACCES00347'
  - 'ACCES00377'
  - 'ACCES00762'
  - 'D0005'
  - 'D0005'
  - 'D0025'
  - 'D0071'
  - 'D0071'
  - 'D0099'
  - 'D0100'
  - 'D0102'
  - 'D0105'
  - 'D0106'
  - 'D0129'
  - 'D0129'
  - 'D0181'
  - 'D0181'
  - 'D0224'
  - 'D0224'
  - 'D0242'
  - 'D0242'
  - 'D0242'
  - 'D0243'
  - 'D0243'
  - 'D0243'
  - 'D0315'
  - 'D0315'
  - 'D0324'
  - 'D0324'
  - 'D0347'
  - 'D0347'
  - 'GUIDE-0001'
  - 'GUIDE-0004'
  - 'GUIDE-0006'
  - 'GUIDE-0016'
  - 'GUIDE-0017'
  - 'GUIDE-0022'
  - 'GUIDE-0031'
  - 'GUIDE-0032'
  - 'GUIDE-0033'
  - 'GUIDE-0034'
  - 'GUIDE-0037'
  - 'GUIDE-0038'
  - 'GUIDE-0039'
  - 'GUIDE-0045'
  - 'GUIDE-0050'
  - 'GUIDE-0058'
  - 'GUIDE-0062'
  - 'GUIDE-0063'
  - 'GUIDE-0068'
  - 'GUIDE-0072'
  - 'GUIDE-0074'
  - 'GUIDE-0076'
  - 'GUIDE-0081'
  - 'GUIDE-0085'
  - 'GUIDE-0086'
  - 'GUIDE-0089'
  - 'GUIDE-0092'
  - 'GUIDE-0093'
  - 'GUIDE-0105'
  - 'GUIDE-0106'
  - 'GUIDE-0111'
  - 'GUIDE-0115'
  - 'GUIDE-0117'
  - 'GUIDE-0118'
  - 'GUIDE-0122'
  - 'GUIDE-0126'
  - 'GUIDE-0127'
  - 'GUIDE-0130'
  - 'GUIDE-0132'
  - 'GUIDE-0135'
  - 'GUIDE-0137'
  - 'GUIDE-0141'
  - 'GUIDE-0142'
  - 'GUIDE-0147'
  - 'GUIDE-0150'
  - 'GUIDE-0153'
  - 'GUIDE-0156'
  - 'GUIDE-0166'
  - 'GUIDE-0168'
  - 'GUIDE-0169'
  - 'GUIDE-0173'
  - 'GUIDE-0178'
  - 'GUIDE-0179'
  - 'GUIDE-0186'
  - 'GUIDE-0187'
  - 'GUIDE-0188'
  - 'GUIDE-0191'
  - 'GUIDE-0192'
  - 'GUIDE-0199'
  - 'GUIDE-0202'
  - 'GUIDE-0208'
  - 'GUIDE-0209'
  - 'GUIDE-0210'
  - 'GUIDE-0212'
  - 'GUIDE-0220'
  - 'GUIDE-0235'
  - 'GUIDE-0237'
  - 'GUIDE-0241'
  - 'GUIDE-0242'
  - 'GUIDE-0247'
  - 'GUIDE-0250'
  - 'GUIDE-0251'
  - 'GUIDE-0254'
  - 'GUIDE-0255'
  - 'GUIDE-0258'
  - 'GUIDE-0259'
  - 'GUIDE-0261'
  - 'GUIDE-0263'
  - 'GUIDE-0266'
  - 'GUIDE-0271'
  - 'GUIDE-0274'
  - 'GUIDE-0278'
  - 'GUIDE-0280'
  - 'GUIDE-0282'
  - 'GUIDE-0284'
  - 'GUIDE-0289'
  - 'GUIDE-0291'
  - 'GUIDE-0298'
  - 'GUIDE-0304'
  - 'GUIDE-0306'
  - 'GUIDE-0309'
  - 'GUIDE-0314'
  - 'GUIDE-0315'
  - 'GUIDE-0321'
  - 'GUIDE-0326'
  - 'GUIDE-0329'
  - 'GUIDE-0331'
  - 'GUIDE-0332'
  - 'GUIDE-0333'
  - 'GUIDE-0334'
  - 'GUIDE-0336'
  - 'GUIDE-0342'
  - 'GUIDE-0343'
  - 'GUIDE-0345'
  - 'GUIDE-0349'
  - 'GUIDE-0351'
  - 'GUIDE-0352'
  - 'GUIDE-0354'
  - 'GUIDE-0356'
  - 'GUIDE-0363'
  - 'GUIDE-0366'
  - 'GUIDE-0368'
  - 'GUIDE-0370'
  - 'GUIDE-0371'
  - 'GUIDE-0372'
  - 'GUIDE-0373'
  - 'GUIDE-0375'
  - 'GUIDE-0376'
  - 'GUIDE-0377'
  - 'GUIDE-0383'
  - 'GUIDE-0385'
  - 'GUIDE-0387'
  - 'GUIDE-0388'
  - 'GUIDE-0391'
  - 'GUIDE-0393'
  - 'GUIDE-0397'
  - 'GUIDE-0401'
  - 'GUIDE-0404'
  - 'GUIDE-0408'
  - 'GUIDE-0411'
  - 'GUIDE-0417'
  - 'GUIDE-0420'
  - 'GUIDE-0423'
  - 'GUIDE-0426'
  - 'GUIDE-0427'
  - 'GUIDE-0429'
  - 'GUIDE-0432'
  - 'GUIDE-0440'
  - 'GUIDE-0441'
  - 'GUIDE-0443'
  - 'GUIDE-0444'
  - 'GUIDE-0446'
  - 'GUIDE-0448'
  - 'GUIDE-0450'
  - 'GUIDE-0452'
  - 'GUIDE-0459'
  - 'GUIDE-0462'
  - 'GUIDE-0463'
  - 'GUIDE-0468'
  - 'GUIDE-0473'
  - 'GUIDE-0474'
  - 'GUIDE-0475'
  - 'GUIDE-0479'
  - 'GUIDE-0480'
  - 'GUIDE-0483'
  - 'GUIDE-0485'
  - 'GUIDE-0486'
  - 'GUIDE-0488'
  - 'GUIDE-0499'
  - 'GUIDE-0501'
  - 'GUIDE-0504'
  - 'GUIDE-0506'
  - 'GUIDE-0507'
  - 'GUIDE-0510'
  - 'GUIDE-0516'
  - 'GUIDE-0519'
  - 'GUIDE-0520'
  - 'GUIDE-0521'
  - 'GUIDE-0525'
  - 'GUIDE-0526'
  - 'GUIDE-0529'
  - 'GUIDE-0534'
  - 'GUIDE-0540'
  - 'GUIDE-0544'
  - 'GUIDE-0546'
  - 'GUIDE-0547'
  - 'GUIDE-0548'
  - 'GUIDE-0551'
  - 'GUIDE-0552'
  - 'GUIDE-0553'
  - 'GUIDE-0557'
  - 'GUIDE-0563'
  - 'GUIDE-0566'
  - 'GUIDE-0570'
  - 'GUIDE-0573'
  - 'GUIDE-0578'
  - 'GUIDE-0581'
  - 'GUIDE-0586'
  - 'GUIDE-0587'
  - 'GUIDE-0588'
  - 'GUIDE-0591'
  - 'GUIDE-0593'
  - 'GUIDE-0595'
  - 'GUIDE-0598'
  - 'GUIDE-0606'
  - 'GUIDE-0607'
  - 'GUIDE-0609'
  - 'GUIDE-0620'
  - 'GUIDE-0626'
  - 'GUIDE-0629'
  - 'GUIDE-0630'
  - 'GUIDE-0632'
  - 'GUIDE-0634'
  - 'GUIDE-0635'
  - 'GUIDE-0636'
  - 'GUIDE-0637'
  - 'GUIDE-0640'
  - 'GUIDE-0646'
  - 'GUIDE-0651'
  - 'GUIDE-0653'
  - 'GUIDE-0657'
  - 'GUIDE-0659'
  - 'GUIDE-0665'
  - 'GUIDE-0671'
  - 'GUIDE-0672'
  - 'GUIDE-0676'
  - 'GUIDE-0677'
  - 'GUIDE-0678'
  - 'GUIDE-0682'
  - 'GUIDE-0689'
  - 'GUIDE-0691'
  - 'GUIDE-0693'
  - 'GUIDE-0696'
  - 'GUIDE-0704'
  - 'GUIDE-0706'
  - 'GUIDE-0707'
  - 'GUIDE-0708'
  - 'GUIDE-0709'
  - 'GUIDE-0710'
  - 'GUIDE-0712'
  - 'GUIDE-0715'
  - 'GUIDE-0716'
  - 'GUIDE-0718'
  - 'GUIDE-0719'
  - 'GUIDE-0720'
  - 'GUIDE-0721'
  - 'GUIDE-0722'
  - 'GUIDE-0725'
  - 'GUIDE-0726'
  - 'GUIDE-0728'
  - 'GUIDE-0729'
  - 'GUIDE-0732'
  - 'GUIDE-0733'
  - 'GUIDE-0734'
  - 'GUIDE-0739'
  - 'GUIDE-0740'
  - 'GUIDE-0742'
  - 'GUIDE-0744'
  - 'GUIDE-0745'
  - 'GUIDE-0746'
  - 'GUIDE-0748'
  - 'GUIDE-0749'
  - 'GUIDE-0750'
  - 'GUIDE-0752'
  - 'GUIDE-0753'
  - 'GUIDE-0754'
  - 'GUIDE-0755'
  - 'GUIDE-0756'
  - 'GUIDE-0757'
  - 'GUIDE-0758'
  - 'GUIDE-0759'
  - 'GUIDE-0761'
  - 'GUIDE-0762'
  - 'GUIDE-0763'
  - 'GUIDE-0765'
  - 'GUIDE-0767'
  - 'GUIDE-0768'
  - 'GUIDE-0769'
  - 'GUIDE-0770'
  - 'GUIDE-0772'
  - 'GUIDE-0775'
  - 'GUIDE-0777'
  - 'GUIDE-0778'
  - 'GUIDE-0779'
  - 'GUIDE-0780'
  - 'GUIDE-0781'
  - 'GUIDE-0782'
  - 'GUIDE-0783'
  - 'GUIDE-0784'
  - 'GUIDE-0785'
  - 'GUIDE-0786'
  - 'GUIDE-0787'
  - 'GUIDE-0788'
  - 'GUIDE-0789'
  - 'GUIDE-0790'
  - 'GUIDE-0793'
  - 'GUIDE-0797'
  - 'GUIDE-0798'
  - 'GUIDE-0799'
  - 'GUIDE-0802'
  - 'GUIDE-0805'
  - 'GUIDE-0806'
  - 'GUIDE-0810'
  - 'GUIDE-0811'
  - 'GUIDE-0812'
  - 'GUIDE-0813'
  - 'GUIDE-0814'
  - 'GUIDE-0815'
  - 'GUIDE-0816'
  - 'GUIDE-0824'
  - 'GUIDE-0827'
  - 'GUIDE-0838'
  - 'GUIDE-0839'
  - 'GUIDE-0840'
  - 'GUIDE-0841'
  - 'GUIDE-0842'
  - 'GUIDE-0843'
  - 'GUIDE-0844'
  - 'GUIDE-0846'
  - 'GUIDE-0848'
  - 'GUIDE-0850'
  - 'GUIDE-0851'
  - 'GUIDE-0855'
  - 'GUIDE-0858'
  - 'GUIDE-0862'
  - 'GUIDE-0863'
  - 'GUIDE-0864'
  - 'GUIDE-0866'
  - 'GUIDE-0871'
  - 'GUIDE-0877'
  - 'GUIDE-0879'
  - 'GUIDE-0880'
  - 'GUIDE-0881'
  - 'GUIDE-0883'
  - 'GUIDE-0888'
  - 'GUIDE-0891'
  - 'GUIDE-0892'
  - 'GUIDE-0893'
  - 'GUIDE-0896'
  - 'GUIDE-0897'
  - 'GUIDE-0902'
  - 'GUIDE-0903'
  - 'GUIDE-0905'
  - 'GUIDE-0909'
  - 'GUIDE-0911'
  - 'GUIDE-0918'
  - 'GUIDE-0919'
  - 'GUIDE-0922'
  - 'GUIDE-0925'
  - 'GUIDE-0927'
  - 'GUIDE-0928'
  - 'GUIDE-0932'
  - 'GUIDE-0933'
  - 'GUIDE-0936'
  - 'GUIDE-0937'
  - 'GUIDE-0942'
  - 'GUIDE-0946'
  - 'GUIDE-0947'
  - 'GUIDE-0957'
  - 'GUIDE-0959'
  - 'GUIDE-0961'
  - 'GUIDE-0962'
  - 'GUIDE-0965'
  - 'GUIDE-0966'
  - 'GUIDE-0967'
  - 'GUIDE-0968'
  - 'GUIDE-0969'
  - 'GUIDE-0972'
  - 'GUIDE-0973'
  - 'GUIDE-0974'
  - 'GUIDE-0976'
  - 'GUIDE-0977'
  - 'GUIDE-0978'
  - 'GUIDE-0979'
  - 'GUIDE-0982'
  - 'GUIDE-0983'
  - 'GUIDE-0986'
  - 'GUIDE-0989'
  - 'GUIDE-0990'
  - 'GUIDE-0993'
  - 'GUIDE-0994'
  - 'GUIDE-1006'
  - 'GUIDE-1008'
  - 'GUIDE-1013'
  - 'GUIDE-1019'
  - 'GUIDE-1022'
  - 'GUIDE-1023'
  - 'GUIDE-1024'
  - 'GUIDE-1025'
  - 'GUIDE-1026'
  - 'GUIDE-1029'
  - 'GUIDE-1030'
  - 'GUIDE-1032'
  - 'GUIDE-1033'
  - 'GUIDE-1035'
  - 'GUIDE-1036'
  - 'GUIDE-1038'
  - 'GUIDE-1040'
  - 'GUIDE-1043'
  - 'GUIDE-1045'
  - 'IOTA001'
  - 'IOTA002'
  - 'IOTA003'
  - 'IOTA004'
  - 'IOTA005'
  - 'IOTA006'
  - 'IOTA007'
  - 'IOTA008'
  - 'IOTA009'
  - 'IOTA010'
  - 'IOTA011'
  - 'IOTA012'
  - 'IOTA013'
  - 'IOTA014'
  - 'IOTA015'
  - 'IOTA016'
  - 'IOTA017'
  - 'IOTA018'
  - 'IOTA019'
  - 'IOTA020'
  - 'IOTA021'
  - 'IOTA022'
  - 'IOTA023'
  - 'IOTA024'
  - 'IOTA025'
  - 'IOTA026'
  - 'IOTA027'
  - 'IOTA028'
  - 'IOTA029'
  - 'IOTA030'
  - 'IOTA031'
  - 'IOTA032'
  - 'IOTA033'
  - 'IOTA034'
  - 'IOTA035'
  - 'IOTA036'
  - 'IOTA037'
  - 'IOTA038'
  - 'IOTA039'
  - 'IOTA040'
  - 'IOTA041'
  - 'IOTA042'
  - 'IOTA043'
  - 'IOTA044'
  - 'IOTA045'
  - 'IOTA046'
  - 'IOTA047'
  - 'IOTA048'
  - 'IOTA049'
  - 'IOTA050'
  - 'IOTA051'
  - 'IOTA052'
  - 'IOTA053'
  - 'IOTA054'
  - 'IOTA055'
  - 'IOTA056'
  - 'IOTA057'
  - 'IOTA058'
  - 'IOTA059'
  - 'IOTA060'
  - 'IOTA061'
  - 'IOTA062'
  - 'IOTA063'
  - 'IOTA064'
  - 'IOTA065'
  - 'IOTA066'
  - 'IOTA067'
  - 'IOTA068'
  - 'IOTA069'
  - 'IOTA070'
  - 'IOTA071'
  - 'IOTA072'
  - 'IOTA073'
  - 'IOTA074'
  - 'IOTA075'
  - 'IOTA076'
  - 'IOTA077'
  - 'IOTA078'
  - 'IOTA079'
  - 'IOTA080'
  - 'IOTA081'
  - 'IOTA082'
  - 'IOTA083'
  - 'IOTA084'
  - 'IOTA085'
  - 'IOTA086'
  - 'IOTA087'
  - 'IOTA088'
  - 'IOTA089'
  - 'IOTA090'
  - 'IOTA091'
  - 'IOTA092'
  - 'IOTA093'
  - 'IOTA094'
  - 'IOTA095'
  - 'IOTA096'
  - 'IOTA097'
  - 'IOTA098'
  - 'IOTA099'
  - 'IOTA100'
  - 'IOTA101'
  - 'IOTA102'
  - 'IOTA103'
  - 'TEST994'
v1_v2_deny_regexes:
  - '^IOTA\d{3}'
  - '^ACCES\d{5}$'
  - '^GUIDE-\d{4}$'
v3_no_partial_claims_models:
  - 'GUIDE'
