codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,files,footer"
  behavior: new
  require_changes: false
  require_base: no
  require_head: no