---
services:
  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.tests
    platform: linux/arm64
    env_file:
      - ./shared_files/decrypted/local.env
    environment:
      - ENV=local
      - DATABASE_URL=postgresql://postgres:toor@db-unit-test:5432/bcda_test?sslmode=disable
      - GOLANGCI_LINT_CACHE=/root/.cache/go-build
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      # Remaining environment variables defined in ./shared_files/decrypted/local.env
    volumes:
      - ./test_results:/go/src/github.com/CMSgov/bcda-app/test_results
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db-unit-test:
        condition: service_started
  db-unit-test:
    image: postgres:16
    # Pass a flag so we'll log all queries executed on the test db.
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bcda_test
    ports:
      - "15432:5432"
    volumes:
      - ./db/testing/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "bcda_test"]
      interval: 40s
      timeout: 15s
      retries: 5
      start_period: 2s
  postman_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.postman_test

networks:
  default:
    name: bcda-app-net
