shadow_mode: false

lambda:
  error_rate_threshold: 1

enabled:
  ecs: true
  sqs: true
  sns: false
  lambda: true
  s3: true
  rds: true
  synthetics: true

health_check:
  enabled: true
  url: "https://sandbox.bcda.cms.gov/_health"
  max_response_time_ms: 1000
  validates_json_path:
    - database
    - ssas
    - ssas_introspect
