enabled:
  ecs: true
  sns: false
  s3: true
  rds: true
  synthetics: true

notifications:
  victorops: false
  slack: true

health_check:
  enabled: true
  url: "https://test.bcda.cms.gov/_health"
  max_response_time_ms: 1000
  validates_json_path:
    - database
    - ssas
    - ssas_introspect

static_site:
  enabled: true
  url: "https://stage.bcda.cms.gov/"
