// Code generated by mockery v2.43.2. DO NOT EDIT.

package worker

import (
	context "context"

	client "github.com/CMSgov/bcda-app/bcda/client"

	mock "github.com/stretchr/testify/mock"

	models "github.com/CMSgov/bcda-app/bcda/models"
)

// MockWorker is an autogenerated mock type for the Worker type
type MockWorker struct {
	mock.Mock
}

// ProcessJob provides a mock function with given fields: ctx, bb, job, jobArgs
func (_m *MockWorker) ProcessJob(ctx context.Context, bb client.APIClient, job models.Job, jobArgs models.JobEnqueueArgs) error {
	ret := _m.Called(ctx, bb, job, jobArgs)

	if len(ret) == 0 {
		panic("no return value specified for ProcessJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.APIClient, models.Job, models.JobEnqueueArgs) error); ok {
		r0 = rf(ctx, bb, job, jobArgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateJob provides a mock function with given fields: ctx, jobArgs
func (_m *MockWorker) ValidateJob(ctx context.Context, jobArgs models.JobEnqueueArgs) (*models.Job, error) {
	ret := _m.Called(ctx, jobArgs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateJob")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.JobEnqueueArgs) (*models.Job, error)); ok {
		return rf(ctx, jobArgs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.JobEnqueueArgs) *models.Job); ok {
		r0 = rf(ctx, jobArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.JobEnqueueArgs) error); ok {
		r1 = rf(ctx, jobArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorker creates a new instance of MockWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorker {
	mock := &MockWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
