"""
Dictionaries that map FHIR R4 to CCLF

These dictionaries are data structures that map the FHIRPath query to the appropriate CCLF column.

cclfX = {
    "COLUMN_NAME"   : ("resource_type", lambda resource: _try_return_first(evaluate(resourse, "Patient.FHIRPath.expression.here", []))),
    "COLUMN_NAME"   : "Not mapped",
}
"""

from fhirpathpy import evaluate


def _try_return_first(l):
    """This is a helper function to handle errors outside the lambda"""
    try:
        return l[0]
    except:
        return ''

cclf1 = {
    "CUR_CLM_UNIQ_ID"               : "Not mapped",
    "PRVDR_OSCAR_NUM"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.contained.where(id = 'provider-org').identifier.where(type.coding.code = 'PRN').value", []))),
    "BENE_MBI_ID"                   : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"                  : "Not mapped",
    "CLM_TYPE_CD"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_FROM_DT"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "CLM_BILL_FAC_TYPE_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.facility.extension('https://bluebutton.cms.gov/resources/variables/clm_fac_type_cd').value.code", []))),
    "CLM_BILL_CLSFCTN_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_srvc_clsfctn_type_cd').valueCoding.code", []))),
    "PRNCPL_DGNS_CD"                : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis.where(type.coding.code = 'principal').diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "ADMTG_DGNS_CD"                 : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis.where(type.coding.code = 'admitting').diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_MDCR_NPMT_RSN_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_mdcr_non_pmt_rsn_cd').valueCoding.code", []))),
    "CLM_PMT_AMT"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.payment.amount.value", []))),
    "CLM_NCH_PRMRY_PYR_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(code.coding.system = 'https://bluebutton.cms.gov/resources/variables/nch_prmry_pyr_cd').code.coding.code", []))),
    "PRVDR_FAC_FIPS_ST_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[0].locationAddress.state", []))),
    "BENE_PTNT_STUS_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(code.coding.system = 'https://bluebutton.cms.gov/resources/variables/ptnt_dschrg_stus_cd').code.coding.code", []))),
    "DGNS_DRG_CD"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(code.coding.system = 'https://bluebutton.cms.gov/resources/variables/clm_drg_cd').code.coding.code", []))),
    "CLM_OP_SRVC_TYPE_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "FAC_PRVDR_NPI_NUM"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.contained.where(id = 'provider-org').identifier.where(type.coding.code = 'npi').value", []))),
    "OPRTG_PRVDR_NPI_NUM"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam.where(role.coding.code = 'operating').provider.identifier.value", []))),
    "ATNDG_PRVDR_NPI_NUM"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam.where(role.coding.code = 'attending').provider.identifier.value", []))),
    "OTHR_PRVDR_NPI_NUM"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam.where(role.coding.code = 'otheroperating').provider.identifier.value", []))),
    "CLM_ADJSMT_TYPE_CD"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.status", []))),
    "CLM_EFCTV_DT"                  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'clmrecvddate')).timingDate", []))),
    "CLM_IDR_LD_DT"                 : "Not mapped",
    "BENE_EQTBL_BIC_HICN_NUM"       : "Not mapped",
    "CLM_ADMSN_TYPE_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.code.where(coding.system = 'https://bluebutton.cms.gov/resources/variables/clm_ip_admsn_type_cd').coding.code", []))),
    "CLM_ADMSN_SRC_CD"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.code.where(coding.system = 'https://bluebutton.cms.gov/resources/variables/clm_src_ip_admsn_cd').coding.code", []))),
    "CLM_BILL_FREQ_CD"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.code.where(coding.system = 'https://bluebutton.cms.gov/resources/variables/clm_freq_cd').coding.code", []))),
    "CLM_QUERY_CD"                  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.extension('https://bluebutton.cms.gov/resources/variables/claim_query_cd').valueCoding.code", []))),
    "DGNS_PRCDR_ICD_IND"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.diagnosis[0].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-10','10',iif(ExplanationOfBenefit.diagnosis[0].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-9','9','U'))", []))),
    "CLM_MDCR_INSTNL_TOT_CHRG_AMT"  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.total.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/clm_tot_chrg_amt')).amount.value", []))),
    "CLM_MDCR_IP_PPS_CPTL_IME_AMT"  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.benefitBalance.financial.where(type.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/clm_pps_cptl_ime_amt')).usedMoney.value", []))),
    "CLM_OPRTNL_IME_AMT"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/ime_op_clm_val_amt').valueMoney.value", []))),
    "CLM_MDCR_IP_PPS_DSPRPRTNT_AMT" : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.benefitBalance.financial.where(type.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/clm_pps_cptl_dsprprtnt_shr_amt')).usedMoney.value", []))),
    "CLM_HIPPS_UNCOMPD_CARE_AMT"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_uncompd_care_pmt_amt').valueMoney.value", []))),
    "CLM_OPRTNL_DSPRTNT_AMT"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/dsh_op_clm_val_amt').valueMoney.value", []))),
}

cclf2 = {
    "CUR_CLM_UNIQ_ID"               : "Not mapped",
    "CLM_LINE_NUM"                  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].sequence", []))),
    "BENE_MBI_ID"                   : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"                  : "Not mapped",
    "CLM_TYPE_CD"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_LINE_FROM_DT"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.item[%n].servicedPeriod.exists(), ExplanationOfBenefit.item[%n].servicedPeriod.start, iif(ExplanationOfBenefit.item[%n].servicedDate.exists(),ExplanationOfBenefit.item[%n].servicedDate,ExplanationOfBenefit.billablePeriod.start))", []))),
    "CLM_LINE_THRU_DT"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.item[%n].servicedPeriod.exists(), ExplanationOfBenefit.item[%n].servicedPeriod.end, iif(ExplanationOfBenefit.item[%n].servicedDate.exists(),ExplanationOfBenefit.item[%n].servicedDate,ExplanationOfBenefit.billablePeriod.end))", []))),
    "CLM_LINE_PROD_REV_CTR_CD"      : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].revenue.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/rev_cntr').code", []))),
    "CLM_LINE_INSTNL_REV_CTR_DT"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.item[%n].servicedPeriod.exists(), ExplanationOfBenefit.item[%n].servicedPeriod.start, iif(ExplanationOfBenefit.item[%n].servicedDate.exists(),ExplanationOfBenefit.item[%n].servicedDate,ExplanationOfBenefit.billablePeriod.start))", []))),
    "CLM_LINE_HCPCS_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].productOrService.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs').code", []))),
    "BENE_EQTBL_BIC_HICN_NUM"       : "Not mapped",
    "PRVDR_OSCAR_NUM"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.contained.where(id = 'provider-org').identifier.where(type.coding.code = 'PRN').value", []))),
    "CLM_FROM_DT"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "CLM_LINE_SRVC_UNIT_QTY"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].quantity.value", []))),
    "CLM_LINE_CVRD_PD_AMT"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/line_prvdr_pmt_amt')).amount.value", []))),
    "HCPCS_1_MDFR_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].modifier[0].where(coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).coding.code", []))),
    "HCPCS_2_MDFR_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].modifier[1].where(coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).coding.code", []))),
    "HCPCS_3_MDFR_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].modifier[2].where(coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).coding.code", []))),
    "HCPCS_4_MDFR_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].modifier[3].where(coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).coding.code", []))),
    "HCPCS_5_MDFR_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].modifier[4].where(coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).coding.code", []))),
    "CLM_REV_APC_HIPPS_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].revenue.where(coding.system = 'https://bluebutton.cms.gov/resources/variables/rev_cntr').coding.code", []))),
}

cclf3 = {
    "CUR_CLM_UNIQ_ID"           : "Not mapped",
    "BENE_MBI_ID"               : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"              : "Not mapped",
    "CLM_TYPE_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_VAL_SQNC_NUM"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.procedure[%n].sequence", []))),
    "CLM_PRCDR_CD"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.procedure[%n].procedureCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_PRCDR_PRFRM_DT"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.procedure[%n].date", []))),
    "BENE_EQTBL_BIC_HICN_NUM"   : "Not mapped",
    "PRVDR_OSCAR_NUM"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.contained.where(id = 'provider-org').identifier.where(type.coding.code = 'PRN').value", []))),
    "CLM_FROM_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "DGNS_PRCDR_ICD_IND"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.procedure[%n].procedureCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-10','10',iif(ExplanationOfBenefit.procedure[%n].procedureCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-9','9','U'))", []))),
}

cclf4 = {
    "CUR_CLM_UNIQ_ID"           : "Not mapped",
    "BENE_MBI_ID"               : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"              : "Not mapped",
    "CLM_TYPE_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_PROD_TYPE_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[%n].type.coding.where(system='https://bluebutton.cms.gov/resources/codesystem/diagnosis-type').code", []))),
    "CLM_VAL_SQNC_NUM"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[%n].sequence", []))),
    "CLM_DGNS_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[%n].diagnosisCodeableConcept.coding.code", []))),
    "BENE_EQTBL_BIC_HICN_NUM"   : "Not mapped",
    "PRVDR_OSCAR_NUM"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.contained.where(id = 'provider-org').identifier.where(type.coding.code = 'PRN').value", []))),
    "CLM_FROM_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "CLM_POA_IND"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[1].extension('https://bluebutton.cms.gov/resources/variables/clm_poa_ind_sw1').valueCoding.code", []))),
    "DGNS_PRCDR_ICD_IND"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.diagnosis[%n].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-10','10',iif(ExplanationOfBenefit.diagnosis[%n].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-9','9','U'))", []))),
}

cclf5 = {
    "CUR_CLM_UNIQ_ID"           : "Not mapped",
    "CLM_LINE_NUM"              : "Not mapped",
    "BENE_MBI_ID"               : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"              : "Not mapped",
    "CLM_TYPE_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_FROM_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "RNDRG_PRVDR_TYPE_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam[ExplanationOfBenefit.item[%n].careTeamSequence-1].extension('https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd').valueCoding.code", []))),
    "RNDRG_PRVDR_FIPS_ST_CD"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].locationCodeableConcept.extension('https://bluebutton.cms.gov/resources/variables/prvdr_state_cd').valueCoding.code", []))),
    "CLM_PRVDR_SPCLTY_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam[ExplanationOfBenefit.item[%n].careTeamSequence-1].qualification.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/prvdr_spclty').code", []))),
    "CLM_FED_TYPE_SRVC_CD"      : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].category.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd').code", []))),
    "CLM_POS_CD"                : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].locationCodeableConcept.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd').code", []))),
    "CLM_LINE_FROM_DT"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].servicedPeriod.start", []))),
    "CLM_LINE_THRU_DT"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].servicedPeriod.end", []))),
    "CLM_LINE_HCPCS_CD"         : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].productOrService.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs').code", []))),
    "CLM_LINE_CVRD_PD_AMT"      : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code ='https://bluebutton.cms.gov/resources/variables/line_nch_pmt_amt')).amount.value", []))),
    "CLM_LINE_PRMRY_PYR_CD"     : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/line_bene_prmry_pyr_cd').valueCoding.code", []))),
    "CLM_LINE_DGNS_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[ExplanationOfBenefit.item[%n].diagnosisSequence-1].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_RNDRG_PRVDR_TAX_NUM"   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/tax_num').valueCoding.code", []))),
    "RNDRG_PRVDR_NPI_NUM"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam[ExplanationOfBenefit.item[%n].careTeamSequence-1].provider.identifier.where(type.coding.where(code = 'npi')).value", []))),
    "CLM_CARR_PMT_DNL_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/carr_clm_pmt_dnl_cd').valueCoding.code", []))),
    "CLM_PRCSG_IND_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd').valueCoding.code", []))),
    "CLM_ADJSMT_TYPE_CD"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.status", []))),
    "CLM_EFCTV_DT"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/nch_wkly_proc_dt')).timingDate", []))),
    "CLM_IDR_LD_DT"             : "Not mapped",
    "CLM_CNTL_NUM"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.identifier.where(system = 'https://bluebutton.cms.gov/resources/variables/clm_id').value", []))),
    "BENE_EQTBL_BIC_HICN_NUM"   : "Not mapped",
    "CLM_LINE_ALOWD_CHRG_AMT"   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/line_alowd_chrg_amt')).amount.value", []))),
    "CLM_LINE_SRVC_UNIT_QTY"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].quantity.value", []))),
    "HCPCS_1_MDFR_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].where(modifier.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).modifier[0].coding.code", []))),
    "HCPCS_2_MDFR_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].where(modifier.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).modifier[1].coding.code", []))),
    "HCPCS_3_MDFR_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].where(modifier.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).modifier[2].coding.code", []))),
    "HCPCS_4_MDFR_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].where(modifier.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).modifier[3].coding.code", []))),
    "HCPCS_5_MDFR_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].where(modifier.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs')).modifier[4].coding.code", []))),
    "CLM_DISP_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.disposition", []))),
    "CLM_DGNS_1_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[0].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_2_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[1].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_3_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[2].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_4_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[3].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_5_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[4].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_6_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[5].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_7_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[6].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_8_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[7].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "DGNS_PRCDR_ICD_IND"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "iif(ExplanationOfBenefit.diagnosis[0].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-10','10',iif(ExplanationOfBenefit.diagnosis[0].diagnosisCodeableConcept.coding.system = 'http://hl7.org/fhir/sid/icd-9','9','U'))", []))),
    "CLM_DGNS_9_CD"             : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[8].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_10_CD"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[9].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_11_CD"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[10].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "CLM_DGNS_12_CD"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.diagnosis[11].diagnosisCodeableConcept.coding.where(system = 'http://hl7.org/fhir/sid/icd-10').code", []))),
    "HCPCS_BETOS_CD"            : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/betos_cd').valueCoding.code", []))),
}

cclf6 = {
    "CUR_CLM_UNIQ_ID"           : "Not mapped",
    "CLM_LINE_NUM"              : "Not mapped",
    "BENE_MBI_ID"               : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"              : "Not mapped",
    "CLM_TYPE_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_FROM_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.start", []))),
    "CLM_THRU_DT"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.billablePeriod.end", []))),
    "CLM_FED_TYPE_SRVC_CD"      : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].category.coding.where(system='https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd').code", []))),
    "CLM_POS_CD"                : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[0].locationCodeableConcept.coding.where(system='https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd').code", []))),
    "CLM_LINE_FROM_DT"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].servicedPeriod.start", []))),
    "CLM_LINE_THRU_DT"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].servicedPeriod.end", []))),
    "CLM_LINE_HCPCS_CD"         : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].productOrService.coding.where(system = 'https://bluebutton.cms.gov/resources/codesystem/hcpcs').code", []))),
    "CLM_LINE_CVRD_PD_AMT"      : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code ='https://bluebutton.cms.gov/resources/variables/line_nch_pmt_amt')).amount.value", []))),
    "CLM_PRMRY_PYR_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/line_bene_prmry_pyr_cd').valueCoding.code", []))),
    "PAYTO_PRVDR_NPI_NUM"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam[ExplanationOfBenefit.item[%n].careTeamSequence-1].provider.identifier.where(type.coding.where(code = 'npi')).value", []))),
    "ORDRG_PRVDR_NPI_NUM"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.referral.identifier.where(type.coding.where(code='npi')).value", []))),
    "CLM_CARR_PMT_DNL_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/carr_clm_pmt_dnl_cd').valueCoding.code", []))),
    "CLM_PRCSG_IND_CD"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].extension('https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd').valueCoding.code", []))),
    "CLM_ADJSMT_TYPE_CD"        : "Not mapped",
    "CLM_EFCTV_DT"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/nch_wkly_proc_dt')).timingDate", []))),
    "CLM_IDR_LD_DT"             : "Not mapped",
    "CLM_CNTL_NUM"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.identifier.where(system = 'https://bluebutton.cms.gov/resources/variables/clm_id').value", []))),
    "BENE_EQTBL_BIC_HICN_NUM"   : "Not mapped",
    "CLM_LINE_ALOWD_CHRG_AMT"   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/line_alowd_chrg_amt')).amount.value", []))),
    "CLM_DISP_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.disposition", []))),
}

ccfl7 = {
    "CUR_CLM_UNIQ_ID"               : "Not mapped",
    "BENE_MBI_ID"                   : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"                  : "Not mapped",
    "CLM_LINE_NDC_CD"               : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].productOrService.coding.where(system='http://hl7.org/fhir/sid/ndc').code", []))),
    "CLM_TYPE_CD"                   : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_LINE_FROM_DT"              : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].servicedDate", []))),
    "PRVDR_SRVC_ID_QLFYR_CD"        : "Not mapped",
    "CLM_SRVC_PRVDR_GNRC_ID_NUM"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.careTeam[ExplanationOfBenefit.item[%n].careTeamSequence-1].where(role.coding.where(code='prescribing')).provider.identifier.where(type.coding.where(code='npi')).value", []))),
    "CLM_DSPNSNG_STUS_CD"           : "Not mapped",
    "CLM_DAW_PROD_SLCTN_CD"         : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.code.where(coding.where(system = 'https://bluebutton.cms.gov/resources/variables/daw_prod_slctn_cd')).code", []))),
    "CLM_LINE_SRVC_UNIT_QTY"        : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].quantity.value", []))),
    "CLM_LINE_DAYS_SUPLY_QTY"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'dayssupply')).valueQuantity.value", []))),
    "PRVDR_PRSBNG_ID_QLFYR_CD"      : "Not mapped",
    "CLM_PRSBNG_PRVDR_GNRC_ID_NUM"  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.facility.identifier.value", []))),
    "CLM_LINE_BENE_PMT_AMT"         : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.item[%n].adjudication.where(category.coding.where(code = 'https://bluebutton.cms.gov/resources/variables/ptnt_pay_amt')).amount.value", []))),
    "CLM_ADJSMT_TYPE_CD"            : "Not mapped",
    "CLM_EFCTV_DT"                  : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'clmrecvddate')).timingDate", []))),
    "CLM_IDR_LD_DT"                 : "Not mapped",
    "CLM_LINE_RX_SRVC_RFRNC_NUM"    : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.identifier.where(system = 'https://bluebutton.cms.gov/resources/variables/rx_srvc_rfrnc_num').value", []))),
    "CLM_LINE_RX_FILL_NUM"          : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code = 'refillnum')).valueQuantity.value", []))),
    "CLM_PHRMCY_SRVC_TYPE_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.facility.extension('https://bluebutton.cms.gov/resources/variables/phrmcy_srvc_type_cd').valueCoding.code", []))),
}

cclf8 = {
    "BENE_MBI_ID"               : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"              : "Not mapped",
    "BENE_FIPS_STATE_CD"        : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.state", []))),
    "BENE_FIPS_CNTY_CD"         : "Not mapped",
    "BENE_ZIP_CD"               : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.postalCode", []))),
    "BENE_DOB"                  : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.birthDate", []))),
    "BENE_SEX_CD"               : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.gender", []))),
    "BENE_RACE_CD"              : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.extension('https://bluebutton.cms.gov/resources/variables/race').valueCoding.code", []))),
    "BENE_AGE"                  : "Not mapped",
    "BENE_MDCR_STUS_CD"         : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.extension('https://bluebutton.cms.gov/resources/variables/ms_cd').valueCoding.code", []))),
    "BENE_DUAL_STUS_CD"         : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.extension('https://bluebutton.cms.gov/resources/variables/dual_01').valueCoding.code", []))),
    "BENE_DEATH_DT"             : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.deceasedDateTime", []))),
    "BENE_RNG_BGN_DT"           : "Not mapped",
    "BENE_RNG_END_DT"           : "Not mapped",
    "BENE_1ST_NAME"             : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.name.given[0]", []))),
    "BENE_MIDL_NAME"            : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.name.given[1]", []))),
    "BENE_LAST_NAME"            : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.name.family", []))),
    "BENE_ORGNL_ENTLMT_RSN_CD"  : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.extension('https://bluebutton.cms.gov/resources/variables/orec').valueCoding.code", []))),
    "BENE_ENTLMT_BUYIN_IND"     : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.extension('https://bluebutton.cms.gov/resources/variables/buyin01').valueCoding.code", []))),
    "BENE_PART_A_ENRLMT_BGN_DT" : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.period.start", []))),
    "BENE_PART_B_ENRLMT_BGN_DT" : ("coverage", lambda obj: _try_return_first(evaluate(obj, "Coverage.period.end", []))),
    "BENE_LINE_1_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[0]", []))),
    "BENE_LINE_2_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[1]", []))),
    "BENE_LINE_3_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[2]", []))),
    "BENE_LINE_4_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[3]", []))),
    "BENE_LINE_5_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[4]", []))),
    "BENE_LINE_6_ADR"           : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.line[5]", []))),
    "GEO_ZIP_PLC_NAME"          : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.city", []))),
    "GEO_USPS_STATE_CD"         : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.state", []))),
    "GEO_ZIP5_CD"               : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.postalCode", []))),
    "GEO_ZIP4_CD"               : ("patient",  lambda obj: _try_return_first(evaluate(obj, "Patient.address.postalCode", []))),
}

cclf9 = {
    "HICN_MBI_XREF_IND" : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').system", []))),
    "CRNT_NUM"          : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "PRVS_NUM"          : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'historic').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "PRVS_ID_EFCTV_DT"  : "Not mapped",
    "PRVS_ID_OBSLT_DT"  : "Not mapped",
    "BENE_RRB_NUM"      : "Not mapped",
}

cclfA = {
    "CUR_CLM_UNIQ_ID"       : "Not mapped",
    "BENE_MBI_ID"           : ("patient", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"          : "Not mapped",
    "CLM_TYPE_CD"           : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
    "CLM_ACTV_CARE_FROM_DT" : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.supportingInfo.where(category.coding.where(code='admissionperiod')).timingPeriod.start", []))),
}

cclfB = {
    "CUR_CLM_UNIQ_ID"   : "Not mapped",
    "CLM_LINE_NUM"      : "Not mapped",
    "BENE_MBI_ID"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value", []))),
    "BENE_HIC_NUM"      : "Not mapped",
    "CLM_TYPE_CD"       : ("eob", lambda obj: _try_return_first(evaluate(obj, "ExplanationOfBenefit.type.coding.where(system = 'https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd').code", []))),
}
