-- SQL script to add Direct Contracting (DC) ACO model participants in production
BEGIN;
INSERT INTO acos (cms_id, name, uuid) VALUES
('D0004','Iora Health NE DCE, LLC',gen_random_uuid ()),
('D0005','ilumed, LLC',gen_random_uuid ()),
('D0006','Arizona Health Advantage, Inc',gen_random_uuid ()),
('D0008','Genuine Health Direct, LLC',gen_random_uuid ()),
('D0011','Renovis Health LLC',gen_random_uuid ()),
('D0013','Vively Health',gen_random_uuid ()),
('D0020','The MetroHealth System dba Collaborative Care Partners',gen_random_uuid ()),
('D0021','ADVANCED VALUE CARE II',gen_random_uuid ()),
('D0025','VillageMD Houston ACO, LLC',gen_random_uuid ()),
('D0027','On Belay Health Solutions, LLC',gen_random_uuid ()),
('D0028','CareMore Aspire Medical Innovation Partners, PC',gen_random_uuid ()),
('D0032','Best Value Healthcare, LLC',gen_random_uuid ()),
('D0033','Texas DCE, Inc.',gen_random_uuid ()),
('D0036','Complete Health Accountable Care LLC',gen_random_uuid ()),
('D0048','Pathways Accountable Care, LLC',gen_random_uuid ()),
('D0056','Ohio DCE - Akron, Inc.',gen_random_uuid ()),
('D0062','Oregon Medicare Direct, Inc',gen_random_uuid ()),
('D0063','Oak Street Health Medicare Partners LLC',gen_random_uuid ()),
('D0067','Northern Michigan Health Network',gen_random_uuid ()),
('D0068','Physicians Healthcare Collaborative',gen_random_uuid ()),
('D0077','Regal Medical Group',gen_random_uuid ()),
('D0078','Central Valley Community Partners LLC',gen_random_uuid ()),
('D0086','American Choice Healthcare, LLC',gen_random_uuid ()),
('D0097','Advanced Illness Partners, LLC',gen_random_uuid ()),
('D0098','Perfect Health DCE, LLC',gen_random_uuid ()),
('D0099','VillageMD Arizona ACO, LLC',gen_random_uuid ()),
('D0100','VillageMD Georgia ACO, LLC',gen_random_uuid ()),
('D0102','VillageMD Primary Providers ACO, LLC',gen_random_uuid ()),
('D0103','Saint Francis Hospital Medicare ACO, LLC',gen_random_uuid ()),
('D0105','VillageMD Michigan ACO, LLC',gen_random_uuid ()),
('D0106','VillageMD New Hampshire ACO, LLC',gen_random_uuid ()),
('D0113','Pittsburgh DCE, Inc.',gen_random_uuid ()),
('D0114','Ohio DCE - Columbus, Inc.',gen_random_uuid ()),
('D0116','Ohio DCE - SEOH, Inc.',gen_random_uuid ()),
('D0124','AdventHealth Senior Care, Inc',gen_random_uuid ()),
('D0129','Assurity DCE LLC',gen_random_uuid ()),
('D0131','CareConnectMD DCE LLC',gen_random_uuid ()),
('D0132','Clover Health Partners LLC',gen_random_uuid ()),
('D0141','AKOS MD IPA, LLC',gen_random_uuid ()),
('D0142','360 Health DCE Inc',gen_random_uuid ()),
('D0143','CenterWell Care Solutions, Inc.',gen_random_uuid ()),
('D0148','United Physicians Association, Inc',gen_random_uuid ()),
('D0152','PeaceHealth Direct Contracting LLC',gen_random_uuid ()),
('D0153','Castell Direct, LLC',gen_random_uuid ()),
('D0155','Space Coast Independent Practice Association, LLC',gen_random_uuid ()),
('D0160','Nivano Physicians, Inc. IPA',gen_random_uuid ()),
('D0162','NEVADA CARE CONNECT',gen_random_uuid ()),
('D0172','Subsero Healthcare, LLC',gen_random_uuid ()),
('D0175','Axceleran DCE1, LLC',gen_random_uuid ()),
('D0178','Axceleran DCE2, LLC',gen_random_uuid ()),
('D0201','Enhanz DCE',gen_random_uuid ()),
('D0203','Humana Direct Contracting Entity, Inc.',gen_random_uuid ());
COMMIT;