-- SQL script to add (KCC) ACO model participants in production
BEGIN;
-- Since we are using Postgres 10, we need to install this extension to generate UUIDs
CREATE EXTENSION "uuid-ossp";
-- Use UUID v4 to match what we are doing when creating an ACO using the bcdacli.
-- It uses uuid.NewRandom() which generates a version 4 UUID.
INSERT INTO acos (cms_id, name, uuid) VALUES
('C0001','Tennessee Valley Kidney Care Alliance LLC',uuid_generate_v4()),
('C0002','Total Kidney Health of Northern California, LLC',uuid_generate_v4()),
('C0003','Gateway Kidney Care KCE, LLC',uuid_generate_v4()),
('C0004','Integrated Kidney Partners I LLC',uuid_generate_v4()),
('C0005','Florida FKP KCE LLC',uuid_generate_v4()),
('C0007','Independence Kidney Care Alliance, LLC',uuid_generate_v4()),
('C0009','Integrated Kidney Care of Pennsylvania and Ohio',uuid_generate_v4()),
('C0010','NANI Patient Care Innovations',uuid_generate_v4()),
('C0011','Integrated Kidney Care of Minnesota, LLC',uuid_generate_v4()),
('C0015','Metropolitan and Capital Region Kidney Care Alliance LLC',uuid_generate_v4()),
('C0016','Alabama Kidney Care Entity, LLC',uuid_generate_v4()),
('C0017','Southeast Kidney Care Entity, LLC',uuid_generate_v4()),
('C0019','Eastern North Carolina Kidney Care Entity, LLC',uuid_generate_v4()),
('C0020','SKI Arizona KCE LLC',uuid_generate_v4()),
('C0022','Heartland Kidney Care Entity, LLC',uuid_generate_v4()),
('C0023','Southern Florida Kidney Care Entity, LLC',uuid_generate_v4()),
('C0025','Northwest Kidney Care Entity, LLC',uuid_generate_v4()),
('C0027','Dallas Kidney Care Entity, LLC',uuid_generate_v4()),
('C0028','Grand Canyon Kidney Care Entity, LLC',uuid_generate_v4()),
('C0029','Michigan Kidney Care Entity, LLC',uuid_generate_v4()),
('C0030','Kentuckiana Kidney Care Entity, LLC',uuid_generate_v4()),
('C0031','Charlotte Kidney Care Entity, LLC',uuid_generate_v4()),
('C0032','Delmarva Kidney Care Entity, LLC',uuid_generate_v4()),
('C0035','Louisissippi Kidney Care Entity, LLC',uuid_generate_v4()),
('C0036','New Jersey Kidney Care Entity, LLC',uuid_generate_v4()),
('C0037','Red River Kidney Care Entity, LLC',uuid_generate_v4()),
('C0038','Central North Carolina Kidney Care Entity, LLC',uuid_generate_v4()),
('C0039','Houston Kidney Care Entity, LLC',uuid_generate_v4()),
('C0040','Las Vegas Kidney Care Entity, LLC',uuid_generate_v4()),
('C0041','Erie Valley Kidney Care Entity, LLC',uuid_generate_v4()),
('C0042','Philadelphia Kidney Care Entity, LLC',uuid_generate_v4()),
('C0044','Carolina Kidney Partners, LLC',uuid_generate_v4()),
('C0048','Integrated Kidney Care of Virginia, LLC',uuid_generate_v4()),
('C0049','Integrated Kidney Care of of New Jersey and Pennsylvania, LLC',uuid_generate_v4()),
('C0050','Integrated Kidney Care of Texas and Oklahoma, LLC',uuid_generate_v4()),
('C0058','Integrated Kidney Care of Nevada, LLC',uuid_generate_v4()),
('C0060','Integrated Kidney Care of Florida, LLC',uuid_generate_v4()),
('C0061','Integrated Kidney Care of South Texas, LLC',uuid_generate_v4()),
('C0062','Integrated Kidney Care of Northern California',uuid_generate_v4()),
('C0063','Tennessee Kidney Care Alliance, LLC',uuid_generate_v4()),
('C0064','Camino Renal Care, LLC',uuid_generate_v4()),
('C0071','Integrated Kidney Partners IV LLC',uuid_generate_v4()),
('C0072','Integrated Kidney Partners VII LLC',uuid_generate_v4()),
('C0073','Integrated Kidney Partners III LLC',uuid_generate_v4()),
('C0074','Integrated Kidney Partners V LLC',uuid_generate_v4()),
('C0078','Kidney Care Center Alliance, LLC',uuid_generate_v4()),
('C0080','Integrated Patient Solutions IPA, LLC',uuid_generate_v4()),
('C0081','Integrated Kidney Care of Georgia, LLC',uuid_generate_v4()),
('C0083','Integrated Kidney Partners II LLC',uuid_generate_v4()),
('C0086','Integrated Kidney Partners VI LLC',uuid_generate_v4()),
('C0088','Integrated Kidney Care of Southern California, LLC',uuid_generate_v4()),
('C0089','Pennsylvania CRAL KCE LLC',uuid_generate_v4()),
('C0090','Integrated Kidney Partners VIII LLC',uuid_generate_v4()),
('C0091','Detroit Kidney Care KCE, LLC',uuid_generate_v4()),
('C0097','West Coast Kidney KCE LLC',uuid_generate_v4()),
('K0003','Venu Kondle, M.D. and Robert Polhemus, M.D. a Medical Corporation, A PC',uuid_generate_v4()),
('K0006','New England Nephrology Home Care Associates',uuid_generate_v4()),
('K0007','PRINE Health Medical Group, PLLC',uuid_generate_v4()),
('K0019','ONEILL CLARK NARVARTE & VICKS A PROFESSIONAL CORPORATION',uuid_generate_v4()),
('K0022','Pacific Kidney & Hypertension, LLC',uuid_generate_v4()),
('K0032','UC Regents, UCLA Dept of Medicine Professional Group',uuid_generate_v4()),
('K0038','Banner University Medical Group -Tucson Nephrology Division',uuid_generate_v4()),
('K0040','RAJESH AGARWALA, M.D., PLLC',uuid_generate_v4()),
('K0041','Nephrology Associates Medical Group, Inc.',uuid_generate_v4()),
('K0045','ADVANCED KIDNEY CARE, M.D., P.A.',uuid_generate_v4()),
('K0051','Southwest Georgia Nephrology Clinic',uuid_generate_v4()),
('K0080','Lynchburg Nephrology Physicians',uuid_generate_v4()),
('K0090','University of Alabama Health Services Foundation, P.C',uuid_generate_v4()),
('K0093','Nephrology Associates of Mobile, P.A.',uuid_generate_v4()),
('K0095','Nephrology Associates of the Merrimack Valley',uuid_generate_v4()),
('K0096','Stony Brook Internists University Faculty Practice Corporation',uuid_generate_v4()),
('K0102','Starling Physicians, PC',uuid_generate_v4()),
('K0103','East Texas Kidney Specialists PA',uuid_generate_v4()),
('K0113','FLORIDA KIDNEY AND HYPERTENSION CARE, P.A.',uuid_generate_v4()),
('K0128','KIDNEY ASSOCIATES OF KANSAS CITY PC',uuid_generate_v4()),
('K0129','KARTHIKEYAN SAI MD PA',uuid_generate_v4()),
('K0136','KIDNEY SPECIALTY CENTER, INC.',uuid_generate_v4()),
('K0138','DIAB AGHA KIDNEY AND HYPERTENSION CLINIC INC',uuid_generate_v4()),
('K0144','Nephrology Consultants of Jacksonville, LLC',uuid_generate_v4()),
('K0145','The Kidney Experts, PLLC',uuid_generate_v4()),
('K0150','KIDNEY SPECIALISTS OF THE PALM BEACHES LLC',uuid_generate_v4()),
('K0153','Kidney Care and Transplant Services of New England, PC',uuid_generate_v4()),
('K0183','Venu Kondle, M.D. and Robert Polhemus, M.D. a Medical Corporation, A PC',uuid_generate_v4()),
('K0184','Venu Kondle, M.D. and Robert Polhemus, M.D. a Medical Corporation, A PC',uuid_generate_v4()),
('K0185','Venu Kondle, M.D. and Robert Polhemus, M.D. a Medical Corporation, A PC',uuid_generate_v4());
('D0012','Temple Center For Population Health, Inc.',uuid_generate_v4()),
('D0015','Rancho Health Management, LLC',uuid_generate_v4()),
('D0019','CareMount Value Partners IPA',uuid_generate_v4()),
('D0034','Indiana University Health ACO, Inc.',uuid_generate_v4()),
('D0042','Central Utah Clinic, P.C.',uuid_generate_v4()),
('D0045','CareAllies Accountable Care Solutions, LLC',uuid_generate_v4()),
('D0051','Piedmont Health Plus',uuid_generate_v4()),
('D0052','Bluerock Care Community LLC',uuid_generate_v4()),
('D0054','EXCELERA DCE',uuid_generate_v4()),
('D0059','St. Lukes Clinic Coordinated Care, Ltd',uuid_generate_v4()),
('D0061','Aetna Integrated Informatics, Inc. d/b/a ActiveHealth',uuid_generate_v4()),
('D0071','Asaar Medical, LLC',uuid_generate_v4()),
('D0081','Midwest DCE, LLC',uuid_generate_v4()),
('D0084','Health Partners for the Elderly LLC',uuid_generate_v4()),
('D0088','Bloom Health Network LLC (d/b/a Bloom Healthcare)',uuid_generate_v4()),
('D0095','ATLAS IPA, LLC',uuid_generate_v4()),
('D0107','agilon health Coastal DCE, Inc.',uuid_generate_v4()),
('D0109','agilon health Northeastern DCE, Inc.',uuid_generate_v4()),
('D0112','Accountable Care Coalition of Southeast Texas, Inc.',uuid_generate_v4()),
('D0115','Accountable Care Coalition of Direct Contracting, LLC',uuid_generate_v4()),
('D0120','Cityblock Health DCE, LLC',uuid_generate_v4()),
('D0127','Q Point Health, LLC (a wholly-owned subsidiary of Equality Health, LLC)',uuid_generate_v4()),
('D0128','24/7 Health Plan Inc',uuid_generate_v4()),
('D0130','Steward Integrated Care Network, Inc.',uuid_generate_v4()),
('D0133','Renown Health',uuid_generate_v4()),
('D0136','Castell Accountable Care, LLC',uuid_generate_v4()),
('D0140','Esse Health ACO, LLC',uuid_generate_v4()),
('D0147','Fairview Health Services',uuid_generate_v4()),
('D0149','SwingHealth Inc.',uuid_generate_v4()),
('D0151','PHYSICIANS PLUS ACO LLC',uuid_generate_v4()),
('D0154','Florence CIN II LLC',uuid_generate_v4()),
('D0156','agilon health Mid-Atlantic DCE, Inc.',uuid_generate_v4()),
('D0163','Sutter Preferred Direct Contracting Entity, LLC.',uuid_generate_v4()),
('D0171','Physician Leaders Direct Contracting Entity, LLC',uuid_generate_v4()),
('D0179','NW Momentum Health Partners ACO',uuid_generate_v4()),
('D0181','Physicians Plus',uuid_generate_v4()),
('D0184','Doctors Choice Medical Group',uuid_generate_v4()),
('D0185','FREEDOM PHYSICIANS CORPORATION',uuid_generate_v4()),
('D0187','Hudson Accountable Care, LLC',uuid_generate_v4()),
('D0207','Park Nicollet Health Services ACO LLC',uuid_generate_v4()),
('D0209','Triad HealthCare Network, LLC.',uuid_generate_v4()),
('D0211','UT Southwestern Accountable Care Network',uuid_generate_v4()),
('D0214','Arizona Care Network - Next, LLC',uuid_generate_v4()),
('D0215','APA ACO Inc.',uuid_generate_v4()),
('D0217','UW Health ACO, Inc.',uuid_generate_v4()),
('D0218','Reliant Medical Group, Inc.',uuid_generate_v4()),
-- Drop the extension since we no longer need to generate UUIDs
DROP EXTENSION "uuid-ossp";
COMMIT;
