// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSSASHTTPClient creates a new instance of MockSSASHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSASHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSASHTTPClient {
	mock := &MockSSASHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSASHTTPClient is an autogenerated mock type for the SSASHTTPClient type
type MockSSASHTTPClient struct {
	mock.Mock
}

type MockSSASHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSASHTTPClient) EXPECT() *MockSSASHTTPClient_Expecter {
	return &MockSSASHTTPClient_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function for the type MockSSASHTTPClient
func (_mock *MockSSASHTTPClient) CreateGroup(groupId string, name string, acoCMSID string) ([]byte, error) {
	ret := _mock.Called(groupId, name, acoCMSID)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return returnFunc(groupId, name, acoCMSID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = returnFunc(groupId, name, acoCMSID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(groupId, name, acoCMSID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSASHTTPClient_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockSSASHTTPClient_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - groupId string
//   - name string
//   - acoCMSID string
func (_e *MockSSASHTTPClient_Expecter) CreateGroup(groupId any, name any, acoCMSID any) *MockSSASHTTPClient_CreateGroup_Call {
	return &MockSSASHTTPClient_CreateGroup_Call{Call: _e.mock.On("CreateGroup", groupId, name, acoCMSID)}
}

func (_c *MockSSASHTTPClient_CreateGroup_Call) Run(run func(groupId string, name string, acoCMSID string)) *MockSSASHTTPClient_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSSASHTTPClient_CreateGroup_Call) Return(bytes []byte, err error) *MockSSASHTTPClient_CreateGroup_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSSASHTTPClient_CreateGroup_Call) RunAndReturn(run func(groupId string, name string, acoCMSID string) ([]byte, error)) *MockSSASHTTPClient_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ResetCredentials provides a mock function for the type MockSSASHTTPClient
func (_mock *MockSSASHTTPClient) ResetCredentials(systemID string) ([]byte, error) {
	ret := _mock.Called(systemID)

	if len(ret) == 0 {
		panic("no return value specified for ResetCredentials")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(systemID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(systemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(systemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSASHTTPClient_ResetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCredentials'
type MockSSASHTTPClient_ResetCredentials_Call struct {
	*mock.Call
}

// ResetCredentials is a helper method to define mock.On call
//   - systemID string
func (_e *MockSSASHTTPClient_Expecter) ResetCredentials(systemID any) *MockSSASHTTPClient_ResetCredentials_Call {
	return &MockSSASHTTPClient_ResetCredentials_Call{Call: _e.mock.On("ResetCredentials", systemID)}
}

func (_c *MockSSASHTTPClient_ResetCredentials_Call) Run(run func(systemID string)) *MockSSASHTTPClient_ResetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSSASHTTPClient_ResetCredentials_Call) Return(bytes []byte, err error) *MockSSASHTTPClient_ResetCredentials_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSSASHTTPClient_ResetCredentials_Call) RunAndReturn(run func(systemID string) ([]byte, error)) *MockSSASHTTPClient_ResetCredentials_Call {
	_c.Call.Return(run)
	return _c
}
