// Code generated by mockery v2.46.3. DO NOT EDIT.

package queueing

import (
	context "context"

	models "github.com/CMSgov/bcda-app/bcda/models"
	mock "github.com/stretchr/testify/mock"
)

// MockEnqueuer is an autogenerated mock type for the MockEnqueuer type
type MockEnqueuer struct {
	mock.Mock
}

// AddAlrJob provides a mock function with given fields: job, priority
func (_m *MockEnqueuer) AddAlrJob(job models.JobAlrEnqueueArgs, priority int) error {
	ret := _m.Called(job, priority)

	if len(ret) == 0 {
		panic("no return value specified for AddAlrJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.JobAlrEnqueueArgs, int) error); ok {
		r0 = rf(job, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddJob provides a mock function with given fields: ctx, job, priority
func (_m *MockEnqueuer) AddJob(ctx context.Context, job models.JobEnqueueArgs, priority int) error {
	ret := _m.Called(ctx, job, priority)

	if len(ret) == 0 {
		panic("no return value specified for AddJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.JobEnqueueArgs, int) error); ok {
		r0 = rf(ctx, job, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddJob provides a mock function with given fields: ctx, job, priority
func (_m *MockEnqueuer) AddPrepareJob(ctx context.Context, job PrepareJobArgs) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for AddJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, PrepareJobArgs) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEnqueuer creates a new instance of MockEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnqueuer {
	mock := &MockEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
