FROM alpine:3.22

RUN addgroup fhir && adduser -D inferno -G fhir && \
    apk update upgrade --no-cache && \
    apk add --no-cache \
        bash \
        curl \
        jq

COPY fhir_testing/config.json .
COPY fhir_testing/run-fhir-test.sh .

RUN chmod +x run-fhir-test.sh

USER inferno

ENTRYPOINT ["./run-fhir-test.sh"]