FROM jekyll/builder

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

WORKDIR /go/src/github.com/CMSgov/bcda-app/bcda-site-static
RUN ["bundle", "install"]
CMD ["bundle", "exec", "jekyll", "build"]