FROM golang:1.11.5

RUN go get -u github.com/tsenart/vegeta

WORKDIR /go/src/github.com/CMSgov/bcda-app/
COPY . .

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/performance_test
CMD ["sh", "performance_test.sh"]