FROM golang:1.10.6

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
RUN go get -u github.com/xo/usql
RUN go get -u github.com/securego/gosec/cmd/gosec
RUN go get -u gotest.tools/gotestsum

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-app
CMD ["bash", "unit_test.sh"]
