FROM golang:1.11-stretch

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
RUN go get -u github.com/xo/usql
RUN go get -u github.com/securego/gosec/cmd/gosec
RUN go get -u gotest.tools/gotestsum
RUN go get -u github.com/tsenart/vegeta

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

RUN dep ensure

RUN apt-get update
RUN apt-get install apt-transport-https ca-certificates libunwind8 icu-devtools python-pip -y

RUN curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
RUN echo "deb https://packagecloud.io/golang-migrate/migrate/debian/ stretch main" > /etc/apt/sources.list.d/migrate.list
RUN apt-get update
RUN apt-get install migrate -y

WORKDIR /go/src/github.com/CMSgov/bcda-app/ssas