FROM golang:1.10.3

RUN go get -u github.com/whytheplatypus/tester

WORKDIR /go/src/github.com/CMSgov/bcda-app/test
COPY . .

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/integration_test
CMD ["tester", "version.toml"]
