FROM golang:1.11.5

ENV GO111MODULE on
WORKDIR /go/src/github.com/CMSgov/bcda-app/
COPY . .

RUN go install github.com/tsenart/vegeta

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/performance_test
CMD ["sh", "performance_test.sh"]