FROM golang:1.11.5-alpine

RUN apk update upgrade
RUN apk add git openssl

RUN openssl genrsa -out /var/local/private.pem 2048
RUN openssl rsa -in /var/local/private.pem -outform PEM -pubout -out /var/local/public.pem

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get github.com/pressly/fresh
RUN go get -u github.com/derekparker/delve/cmd/dlv

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .
RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-app/ssas
CMD ["fresh", "-r", "start"]
