FROM golang:1.11.5

RUN openssl genrsa -out /var/local/private.pem 2048
RUN openssl rsa -in /var/local/private.pem -outform PEM -pubout -out /var/local/public.pem

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .


ENV GO111MODULE on

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint
RUN go install github.com/xo/usql
RUN go install github.com/securego/gosec/cmd/gosec
RUN go install gotest.tools/gotestsum
RUN go install github.com/tsenart/vegeta

ENV BCDA_ERROR_LOG /var/log/bcda-error.log
ENV BCDA_REQUEST_LOG /var/log/bcda-request.log
ENV BCDA_BB_LOG /var/log/bcda-bb-request.log
ENV BB_CLIENT_CERT_FILE ../shared_files/bb-dev-test-key.pem
ENV BB_CLIENT_KEY_FILE ../shared_files/bb-dev-test-key.pem
ENV BB_SERVER_LOCATION https://fhir.backend.bluebutton.hhsdevcloud.us
ENV FHIR_PAYLOAD_DIR ../bcdaworker/data
ENV FHIR_STAGING_DIR ../bcdaworker/tmpdata

WORKDIR /go/src/github.com/CMSgov/bcda-app
CMD ["bash", "unit_test.sh"]
