FROM golang:1.11.5

RUN go get -u github.com/golang/dep/cmd/dep
WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger
RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-app/bcda
CMD ["swagger", "generate", "spec", "-o", "swaggerui/swagger.json", "-m"]