# syntax = docker/dockerfile:1-experimental
FROM golang:1.19-alpine3.15

RUN apk update upgrade

RUN apk add bash build-base curl

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /go/src/github.com/CMSgov/bcda-app


# Download all dependencies
COPY go.mod go.sum tools.go ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download
RUN --mount=type=cache,target=/go/pkg/mod \
    cat tools.go | awk '/[\/\/] test/{flag=1; next} /[\/\/] end/{flag=0} flag' | awk -F '"' '{print $2}' | xargs -tI % go get %

RUN go install github.com/securego/gosec/v2/cmd/gosec@v2.12.0
RUN go install gotest.tools/gotestsum@v1.8.1

COPY . .
WORKDIR /go/src/github.com/CMSgov/bcda-app
ENTRYPOINT []
