FROM python:3.7-alpine3.8

ARG GITHUB_ACCESS_TOKEN
ARG GITHUB_USER
ARG GITHUB_EMAIL
ARG GITHUB_GPG_KEY_FILE

RUN apk update
RUN apk add --no-cache bash git gnupg

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

ENTRYPOINT ["bash", "ops/release.sh"]
CMD []
