FROM golang:1.11.5-alpine

RUN apk update upgrade
RUN apk add git

RUN go get -u github.com/tsenart/vegeta

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/performance_test
COPY ./test/performance_test .

CMD ["sh", "performance_test.sh"]
