FROM golang:1.10.3

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get github.com/pressly/fresh
RUN go get -u github.com/derekparker/delve/cmd/dlv

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .
RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-app/bcdaworker
CMD ["fresh"]
