FROM golang:1.10.3

RUN go get github.com/tools/godep
RUN go get github.com/pressly/fresh
RUN go get -u github.com/derekparker/delve/cmd/dlv
RUN go get -u github.com/jinzhu/gorm

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .
RUN godep restore ./...

WORKDIR /go/src/github.com/CMSgov/bcda-app/bcdaworker
CMD ["fresh"]
