FROM golang:1.10-alpine3.8

RUN apk upgrade
RUN apk update
RUN apk add --no-cache gcc make ruby ruby-dev rpm libc-dev git
RUN gem install --no-ri --no-rdoc fpm etc
RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-app/ops
RUN chmod u+x build_and_package.sh

ENTRYPOINT ["sh", "build_and_package.sh"]
CMD []
