FROM alpine:3.22

RUN apk add --no-cache curl jq bash

COPY fhir_testing/config.json .
COPY fhir_testing/run-fhir-test.sh .

RUN chmod +x run-fhir-test.sh

RUN addgroup fhir && adduser -D inferno -G fhir
USER inferno

ENTRYPOINT ["./run-fhir-test.sh"]