FROM golang:1.11.5-alpine

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/smoke_test
COPY ./test/smoke_test .

WORKDIR /go/src/github.com/CMSgov/bcda-app/shared_files
COPY ./shared_files .

WORKDIR /go/src/github.com/CMSgov/bcda-app/test/smoke_test
CMD ["sh", "smoke_test.sh"]
