FROM node:current-slim

WORKDIR '/'

RUN apt update -y && apt install curl jq git vim -y

RUN git clone https://github.com/smart-on-fhir/bdt.git
WORKDIR '/bdt'

COPY bdt/config.js .
COPY bdt/run-bdt.sh .

RUN npm install

CMD ["./run-bdt.sh"]