FROM postman/newman
WORKDIR /go/src/github.com/CMSgov/bcda-app/test/postman_test
COPY ./test/postman_test .
WORKDIR /go/src/github.com/CMSgov/bcda-app/
ENV NODE_OPTIONS "--max-old-space-size=2048"
ENTRYPOINT ["newman", "run"]
