name: Admin Create ACO Credentials Integration Tests GF

on:
  pull_request:
    paths:
      - .github/workflows/admin-create-aco-creds-integration-test.yml
      - .github/workflows/admin-create-aco-creds-deploy.yml
      - bcda/lambda/admin_create_aco_creds/**
  workflow_dispatch:

# Ensure we have only one integration test running at a time
concurrency:
  group: admin-create-aco-creds-integration-test

jobs:
  # Deploy first if triggered by pull_request
  deploy:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/admin-create-aco-creds-deploy.yml
    secrets: inherit    
    with:
      deploy_env: dev

  trigger:
    if: ${{ always() }}
    needs: deploy
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: ./bcda/lambda/admin_create_aco_creds
    outputs:
      start_time: ${{ steps.invoke-lambda.outputs.STARTTIME }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-dev-github-actions
      - name: Send event to trigger lambda function
        id: invoke-lambda
        run: |
          echo "STARTTIME=`date +%s`" >> "$GITHUB_OUTPUT"
          aws lambda invoke --function-name bcda-dev-admin-create-aco-creds \
            --cli-binary-format raw-in-base64-out \
            --payload '{"aco_id":"A0012","ips":["1.2.3.4", "9ce6:209a:0bb0:bcdc:3693:68ba:54f9:94d0"]}' test-result.txt
      - name: Verify result
        run: |
          if grep -q "errorType" test-result.txt; then echo "Failed: check lambda logs."; exit 1; else echo "Success"; fi

