name: Admin ACO Deny dev deploy

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bcda/lambda/admin_aco_deny/**
      - .github/workflows/admin-aco-deny-dev-deploy.yml

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bcda
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build admin-aco-deny zip file
        env:
          CGO_ENABLED: 0
        run: |
          go build -o bin/bootstrap ./lambda/admin_aco_deny/main.go
          zip -j function.zip bin/bootstrap
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-dev-github-actions
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress function.zip \
            s3://bcda-dev-admin-aco-deny-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-dev-admin-aco-deny \
            --s3-bucket bcda-dev-admin-aco-deny-function --s3-key function-${{ github.sha }}.zip
