name: Admin ACO Deny deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment you want to deploy to (dev, test, opensbx, prod)'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - opensbx
          - prod
  push:
    branches:
      - main
    paths:
      - bcda/lambda/admin_aco_deny/**
      - .github/workflows/admin-aco-deny-deploy-GF.yml
  pull_request:

jobs:
  build_and_zip:
    #if: ${{ github.event_name == 'merge' }} || ${{ inputs.env == "dev" }} || || ${{ inputs.env == "test" }}
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: bcda
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build admin-aco-deny zip file
        env:
          CGO_ENABLED: 0
        run: |
          go build -o bin/bootstrap ./lambda/admin_aco_deny/*.go
          zip -j function.zip bin/bootstrap
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.account_id] }}:role/delegatedadmin/developer/bcda-dev-github-actions # update this for prod later
      - name: Upload and reload
        run: |
          ENVIRONMENT=${{ inputs.env }}
          if [[ -z ENVIRONMENT ]]; then
            ENVIRONMENT="dev"
          fi
          echo $ENVIRONMENT
          # aws s3 cp --no-progress function.zip \
          #   s3://bcda-$ENVIRONMENT-admin-aco-deny-function/function-${{ github.sha }}.zip
          # aws lambda update-function-code --function-name bcda-$ENVIRONMENT-admin-aco-deny \
          #   --s3-bucket bcda-$ENVIRONMENT-admin-aco-deny-function --s3-key function-${{ github.sha }}.zip
