name: Admin ACO Deny deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Environment you want to deploy to (dev, test, sandbox, prod)'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
  push:
    branches:
      - main
    paths:
      - bcda/lambda/admin_aco_deny/**
      - .github/workflows/admin-aco-deny-deploy.yml


env:
  RELEASE_ENV: ${{ inputs.env || 'dev' }}

jobs:
  deploy_tf:
    runs-on: codebuild-bcda-app-${{ contains(fromJSON('["prod", "sandbox"]'), inputs.deploy_env) && 'prod' || 'non-prod'}}-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/delegatedadmin/developer/${{ vars.AWS_ROLE_TO_ASSUME }}
      - name: Get AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            GITHUB_TOKEN=/ci/github/token
      - name: Checkout BCDA
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          repository: CMSgov/bcda-app
      - name: Install Cosign to verify tenv and tofu installs
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 #v4.1.1@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
      - name: Install tenv
        uses: cmsgov/cdap/actions/setup-tenv@0b65099ef9232cfa2dfd4eea89cf8b9fa6052013
      - name: Install OpenTofu
        working-directory: ops/services/30-admin-aco-deny
        run: tenv tofu install
      - name: Init, Plan OpenTofu
        working-directory: ops/services/30-admin-aco-deny
        run: |
          TF_WORKSPACE=default tofu init -var parent_env=${{ env.RELEASE_ENV }} -reconfigure && tofu workspace select -var parent_env=${{ env.RELEASE_ENV }} -or-create ${{ env.RELEASE_ENV }}
          tofu plan \
            -out 'bcda-release-lambda.tfplan'
      - name: OpenTofu Apply
        working-directory: ops/services/30-admin-aco-deny
        run: |
          tofu apply bcda-release-lambda.tfplan

  deploy_function:
    needs: [deploy_tf]
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-bcda-app-${{ contains(fromJSON('["prod", "sandbox"]'), inputs.deploy_env) && 'prod' || 'non-prod'}}-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: bcda
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build admin-aco-deny zip file
        env:
          CGO_ENABLED: 0
        run: |
          env GOOS=linux GOARCH=arm64 go build -o bin/bootstrap ./lambda/admin_aco_deny/*.go
          zip -j function.zip bin/bootstrap
      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-${{ vars.AWS_ROLE_TO_ASSUME }}-github-actions
      - name: Get Bucket
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            BUCKET=/bcda/${{ env.RELEASE_ENV }}/admin-aco-deny-bucket
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress function.zip \
            s3://$BUCKET/function-${{ github.sha }}.zip
          aws s3api put-object-tagging \
            --bucket $BUCKET \
            --key function-${{ github.sha }}.zip \
            --tagging 'TagSet=[{Key=lifecycle-transition,Value=ia}]'
          aws lambda update-function-code --function-name bcda-${{ env.RELEASE_ENV }}-admin-aco-deny \
            --s3-bucket $BUCKET --s3-key function-${{ github.sha }}.zip

