name: Admin Create Group Test Deploy

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bcda/lambda/create_group/**
      - .github/workflows/admin-create-group-test-deploy.yml

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bcda
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build create-group zip file
        env:
          CGO_ENABLED: 0
        run: |
          go build -o bin/bootstrap ./lambda/admin_create_group/*.go
          zip -j function.zip bin/bootstrap
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress function.zip \
            s3://bcda-test-create-group-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-test-create-group \
            --s3-bucket bcda-test-create-group-function --s3-key function-${{ github.sha }}.zip
