name: Archive and Clean Job Data opensbx deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-dev-github-actions
      - name: Promote lambda code from opensbx to prod
        run: |
          aws s3 cp --no-progress function.zip \
            s3://bcda-opensbx-archive-clean-job-data-function/function-${{ github.sha }}.zip \
            s3://bcda-prod-archive-clean-job-data-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-prod-archive-clean-job-data \
            --s3-bucket bcda-prod-archive-clean-job-data-function --s3-key function-${{ github.sha }}.zip
