# Build AMI will create a 'platinum ami' using packer and ansible that is based off of the CMS monthly Gold Image.
name: Build AMI GF

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  build_ami:
    name: build the platinum ami
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: hashicorp/setup-packer@v2.0.1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            GITHUB_TOKEN=/ci/github/token
            SUBNET_ID=/bcda/workflows/packer_subnet_id
            GOLD_IMAGE=/bcda/workflows/gold_image_ami
      - name: checkout bcda-ops
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-ops
          ref: 'main'
          token: ${{ env.GITHUB_TOKEN }}
      - name: Install Ansible
        run: |
          sudo yum update -y
          sudo yum install python3-pip -y
          python3 -m pip install ansible==6.5.0
      - name: packer build
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMPDIR: /home/ec2-user/
        run: |
          set -euo pipefail
          packer init packer/platinum.json.pkr.hcl 2>&1
          packer build -color=false -var "source_ami=${GOLD_IMAGE}" -var "subnet_id=${SUBNET_ID}" packer/platinum.json.pkr.hcl 2>&1
