name: Build AMI

# on:
#   schedule:
#     - cron: "H 23 * * *"
# below trigger will be modified after testing
on:
  pull_request:
    paths:
      - .github/workflows/build-ami.yml

permissions:
  id-token: write
  contents: read

jobs:
  build_ami:
    name: build ami
    runs-on: self-hosted
    steps:
      - uses: hashicorp/setup-packer@v2.0.1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            GITHUB_TOKEN=/ci/github/token
            SUBNET_ID=/bcda/workflows/packer_subnet_id
            GOLD_IMAGE=/bcda/workflows/gold_image_ami
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: cmsgov/ab2d-bcda-dpc-platform
          ref: 'main'
          path: ./platformrepo
      - name: copy packer config
        run: |   
          mkdir ${{ github.workspace }}/packer-config
          cp -a ./platformrepo/packer/. ${{ github.workspace }}/packer-config
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          repository: CMSgov/bcda-ops
          ref: 'main'
          token: ${{ env.GITHUB_TOKEN }}
      - name: packer build
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMPDIR: /home/ec2-user/
        run: |
          # set -euo pipefail to ensure internal packer/ansible failures get passed to the jenkins pipeline and fails that jobstep
          set -euo pipefail
          ls ${{ github.workspace }}/
          #ls $GITHUB_WORKSPACE/
          pwd
          # packer init ${{ github.workspace }}/packer-config/github-actions-runner/
          #USER=`whoami` PACKER_LOG=1 packer build -color=false -var 'source_ami=$GOLD_IMAGE' -var 'subnet_id=$SUBNET_ID' packer/platinum.json 2>&1 | tee platinum_packer_output.txt

