name: Build and Package BCDA

on:
  workflow_call:
    inputs:
      release_version:
        description: 'Release version (or branch name)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (or branch name)'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  ci_checks:
    uses: ./.github/workflows/ci-checks.yml
    with:
      # release_version: ${{ inputs.release_version }}
      release_version: carl/BCDA-8633-build-bcda-on-ami

  build_and_package:
    uses: ./.github/workflows/package-rpms.yml
    with:
      # release_version: ${{ inputs.release_version }}
      release_version: carl/BCDA-8633-build-bcda-on-ami
  
  post_build:
    if: ${{ always() }}
    name: Post Build (Cleanup, Alerts)
    runs-on: self-hosted
    steps:
      - name: Success Alert
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-deploy
          payload: |
            channel: "C03S23MJFJS"
            attachments:
              - color: good
                text: "SUCCESS: Build and Package BCDA/Worker (run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }})>"
                mrkdown_in:
                  - text
      # TODO: junit 'bcda-app/test_results/latest/junit.xml'
      - name: Failure Alert
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-alerts
          payload: |
            channel: "C034CFU945C"
            attachments:
              - color: danger
                text: "FAILURE: Build and Package BCDA/Worker (run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }})>"
                mrkdown_in:
                  - text
