name: Build AMI

# on:
#   schedule:
#     - cron: "H 23 * * *"
# below trigger will be modified after testing
on:
  pull_request:
    paths:
      - .github/workflows/build-ami.yml

permissions:
  id-token: write
  contents: read

jobs:
  build_ami:
    name: build ami
    runs-on: self-hosted
    steps:
      - uses: hashicorp/setup-packer@v2.0.1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            GITHUB_TOKEN=/ci/github/token
            SUBNET_ID=/bcda/workflows/packer_subnet_id
            GOLD_IMAGE=/bcda/workflows/gold_image_ami
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-ops
          ref: 'main'
          token: ${{ env.GITHUB_TOKEN }}

      - name: packer build
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMPDIR: /home/ec2-user/
        run: |
          packer init .
          # Security groups must be set by flag since they're a list
          packer validate -evaluate-datasources -var "security_group_ids=$SUBNET_ID" .
          ${RUNNER_DEBUG:+"PACKER_LOG=1"} packer build -var "security_group_ids=$SUBNET_ID" .
