# Build and Package will build and package BCDA and SSAS APIs onto one platinum AMI and BCDA Worker onto another plat AMI
name: Build and Package

on:
  push:
    branches: carl/BCDA-8633-build-bcda-on-ami
  # workflow_call:
  #   inputs:
  #     release_version:
  #       description: 'Release version (or branch name)'
  #       required: true
  #       type: string
  #     env:
  #       description: 'Release env'
  #       required: true
  #       default: 'dev'
  #       type: string
  # workflow_dispatch:
  #   inputs:
  #     release_version:
  #       description: 'Release version (or branch name)'
  #       required: true
  #       type: string
  #     env:
  #       description: 'Release env'
  #       required: true
  #       default: 'dev'
  #       type: choice
  #       options:
  #         - dev
  #         - test
  #         - sbx
  #         - prod

permissions:
  id-token: write
  contents: read

jobs:
  build_and_package:
    name: Build and package BCDA, SSAS, and BCDA Worker
    runs-on: self-hosted
    steps:
      # - name: Clear working dir
      - name: Checkout BCDA (SSAS?, OPS?)
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-app
          # ref: ${{ inputs.release_version }}
          ref: carl/BCDA-8633-build-bcda-on-ami
      - name: Build and Package BCDA
        uses: ./.github/workflows/build-and-package-bcda.yml
        with:
          # release_version: ${{ inputs.release_version }}
          release_version: carl/BCDA-8633-build-bcda-on-ami
          # env: ${{ inputs.env }}
          env: dev
      - name: Build and Package SSAS
        uses: CMSgov/bcda-ssas-app/.github/workflows/build-and-package.yml@carl/BCDA-8633-build-bcda-on-ami
        with:
          # release_version: ${{ inputs.release_version }}
          release_version: carl/BCDA-8633-build-bcda-on-ami
          # env: ${{ inputs.env }}
          env: dev
      - name: Get platinum AMI
      - name: Create API AMI
      - name: Create Worker AMI
			# - name: Get AMIs
      # - name: Run migrations (BCDA)
      # - name: Run migrations (SSAS)
      # - name: Deploy to {env}
