name: Build AMI

# on:
#   schedule:
#     - cron: "H 23 * * *"
# below trigger will be modified after testing
on:
  pull_request:
    paths:
      - .github/workflows/build-ami.yml

permissions:
  id-token: write
  contents: read

jobs:
  get_packer_configs:
    name: get packer configs
    runs-on: self-hosted
    steps:
      - name: checkout platform repo
        uses: actions/checkout@v4
        with: 
          repository: cmsgov/ab2d-bcda-dpc-platform
          ref: 'main'
      - name: upload packer configs
        uses: actions/upload-artifact@v4
        with:
          name: packer-configs
          path: ./packer/github-actions-runner/
  build_ami:
    name: build the platinum ami
    runs-on: self-hosted
    needs: get_packer_configs
    steps:
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            GITHUB_TOKEN=/ci/github/token
            SUBNET_ID=/bcda/workflows/packer_subnet_id
            GOLD_IMAGE=/bcda/workflows/gold_image_ami
      - name: checkout bcda-ops
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-ops
          ref: 'lauren/BCDA-8635'
          token: ${{ env.GITHUB_TOKEN }}

      - name: download packer configs
        uses: actions/download-artifact@v4
      - name: Install python
        uses: actions/setup-python@v4
      - name: Install pipx #6.5.0
        run: python3 -m pip install --user pipx
      - name: Install ansible #6.5.0
        run: pipx install --include-deps ansible==6.5.0
      - name: packer build
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #TMPDIR: /home/ec2-user/
        run: |
          # set -euo pipefail to ensure internal packer/ansible failures get passed to the jenkins pipeline and fails that jobstep
          set -euo pipefail
          packer init packer/platinum.json.pkr.hcl 2>&1
          packer build -color=false -var "source_ami=${GOLD_IMAGE}" -var "subnet_id=${SUBNET_ID}" packer/platinum.json.pkr.hcl 2>&1

