name: cclf-import unit tests

on:
  pull_request:
    paths:
      - .github/workflows/cclf-import-unit.yml
      - lambda/cclf-import/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda/cclf-import
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run unit tests for cclf-import lambda
        run: make unit-test
