name: cclf-import test deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bcda
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build cclf-import zip file
        env:
          CGO_ENABLED: 0
        run: |
          go build -o bin/cclf-import ./lambda/cclf/main.go
          zip function.zip bootstrap
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress function.zip \
            s3://bcda-test-cclf-import-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-test-cclf-import \
            --s3-bucket bcda-test-cclf-import-function --s3-key function-${{ github.sha }}.zip
