name: CI Checks GF

on:
  push:
    branches:
      - main
      - "jscott/PLT-1052"
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_version:
        description: 'Release version (or branch name)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (or branch name)'
        required: true
        type: string

env:
  RELEASE_VERSION: ${{ inputs.release_version || github.sha }}

jobs:
  go_mod_tidy:
    name: Modules Lint
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-app
          ref: ${{ env.RELEASE_VERSION }}
      - name: Get Go # TEMP
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.1'
      - name: Tidy modules
        run: |
          go mod tidy -v
          CHANGES_FOUND=$(git diff-files --quiet)
          if [[ "$(CHANGES_FOUND)" == "1" ]]; then
            echo "Changes found. Run go mod tidy to clean up modules."
            git diff
            exit 1
          fi

  lint_and_test:
    name: Lint and Test
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Get Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.1'
      - name: Install docker compose manually
        run: |
          echo "Attempt to start docker"
          sudo systemctl start docker
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.35.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-app
          ref: ${{ env.RELEASE_VERSION }}
      - name: Set up Ansible
        run: |
          sudo dnf -y install python3 python3-pip
          pip install ansible
      - name: Decrypt secrets
        env:
          VAULT_PW: ${{ secrets.VAULT_PW }}
        run: |
          echo "$VAULT_PW" > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Build the stack
        run: make docker-bootstrap
      - name: Lint and Test
        run: make test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./test_results/latest/testcoverage.out
      - name: Cleanup secrets
        if: ${{ always() }}
        run: rm -rf shared_files/decrypted shared_files/encrypted .vault_password

  sonar-quality-gate:
    name: Sonarqube Quality Gate
    needs: lint_and_test
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-app
          fetch-depth: 0
      - name: Download code coverage
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
      - name: Run quality gate scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args:
            -Dsonar.projectKey=bcda-aco-api
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=testcoverage.out
            -Dsonar.coverage.exclusions=**/*test.go,**/test/**/*,**/testUtils/*,**/scripts/*,**/ops/*,**/mock*.go,**/mock/**/*
            -Dsonar.branch.name=${{ env.RELEASE_VERSION }}
            -Dsonar.projectVersion=${{ github.sha }}
            -Dsonar.qualitygate.wait=true
