name: BCDA CI Workflow

on: [push]

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  VAULT_PW: ${{ secrets.VAULT_PW }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-20210422-01-${{ hashFiles('**/go.sum') }}
      - name: Show file tree
        run: tree -dL 3 /
      - name: Show runner temp dir
        run: echo ${{ runner.temp }}
      # - name: Build the stack
      #   run: |
      #     make docker-bootstrap
      # - name: Run all tests
      #   run: |
      #     make test
      # - name: Generate codecov report
      #   uses: codecov/codecov-action@v1
      #   with:
      #     files: ./test_results/latest/testcoverage.out # optional
      #     flags: unittests # optional
      #     name: codecov-umbrella # optional
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
