name: BCDA CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  VAULT_PW: ${{ secrets.VAULT_PW }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the stack
        run: |
          make docker-bootstrap
      - name: Run Lint
        run: |
          make lint
  unittest:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    name: Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the stack
        run: |
          make docker-bootstrap
      - name: Run Unit-Test and Generate Codecov Report
        run: |
          make unit-test
      - name: Generate codecov report
        uses: codecov/codecov-action@v1
        with:
          files: ./test_results/latest/testcoverage.out # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
  postman:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    name: Postman
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the stack
        run: |
          make docker-bootstrap
      - name: Run Unit-Test and Generate Codecov Report
        run: |
          make postman env=local
  smoketest:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    name: Smoke Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the stack
        run: |
          make docker-bootstrap
      - name: Run Unit-Test and Generate Codecov Report
        run: |
          make smoke-test
