name: "BCDA CI Workflow"

on: [push]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1
      - name: "Decrypt secrets"
      - run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: "Build the stack"
        run: |
          make docker-bootstrap
      - name: "Run all tests"
        run: |
          make test
