name: "BCDA CI Workflow"

on: [push]

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  VAULT_PW: ${{ secrets.VAULT_PW }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1
      - name: "Decrypt secrets"
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: "Build the stack"
        run: |
          make docker-bootstrap
      - name: "Run all tests"
        run: |
          make test

  snyk:
    name: "Run Snyk Workflow"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Run Snyk - Golang"
      uses: snyk/actions/golang@master
      continue-on-error: false
      with:
        command: test
        args: --severity-threshold=high
    - name: Build Docker Images
      run: |
        docker build -f Dockerfiles/Dockerfile.package -t bcda-package
        docker build -f Dockerfiles/Dockerfile.bdt -t bcda-bdt
        docker build -f Dockerfiles/Dockerfile.tests -t bcda-tests
    - name: "Run Snyk - Docker"
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: bcda-package
        args: --file=Dockerfiles/Dockerfile.package --severity-threshold=high
    - name: "Run Snyk - Docker"
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: bcda-bdt
        args: -file=Dockerfiles/Dockerfile.bdt --severity-threshold=high
    - name: "Run Snyk - Docker"
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: bcda-tests
        args: --file=Dockerfiles/Dockerfile.tests --severity-threshold=high

