name: BCDA CI Workflow

on: [push]

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  VAULT_PW: ${{ secrets.VAULT_PW }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Go paths for cache
        run: |
          mkdir -p $HOME/work/bcda-app/mod
          mkdir -p $HOME/work/bcda-app/cache
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/
      - name: Retrieve Go build cache
        uses: actions/cache@v2
        with:
          #path: ${{ steps.go-cache-paths.outputs.go-build-cache }}
          path: /home/runner/work/bcda-app/cache
          key: ${{ runner.os }}-go-build-test3-${{ hashFiles('**/go.sum') }}
      - name: Retrieve Go mod cache
        uses: actions/cache@v2
        with:
          #path: ${{ steps.go-cache-paths.outputs.go-mod-cache }}
          path: /home/runner/work/bcda-app/mod
          key: ${{ runner.os }}-go-mod-test3${{ hashFiles('**/go.sum') }}
      - name: Find files
        run: |
          tree -daL 3 /home/runner/work/
          tree -daL 3 /home/runner/go/
          echo ${{ steps.go-cache-paths.outputs.go-build-cache }}
          echo ${{ steps.go-cache-paths.outputs.go-mod-cache }}
      - name: Build the stack
        run: |
          whoami
          pwd
          make docker-bootstrap
      - name: Run all tests
        run: |
          echo "testing"
          #make test
      - name: Find files after build and test
        run: |
          tree -daL 3 /home/runner/work/
          tree -daL 3 /home/runner/go/
          echo ${{ steps.go-cache-paths.outputs.go-build-cache }}
          echo ${{ steps.go-cache-paths.outputs.go-mod-cache }}

