# This workflow generates database documentation and ERD files.
#
name: Generate dbdocs

on:
  pull_request:
    # paths:
    #   - .github/workflows/dbdocs.yml
    #   - db/migrations/bcda
    #   - db/migrations/bcda_queue

env:
  VAULT_PW: ${{ secrets.VAULT_PW }}

jobs:
  generate-docs:
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Ansible
        run: |
          sudo dnf install ansible
      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/

      - name: Start DB
        run: make reset-db

      - name: Generate DB docs
        run: make dbdocs

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: dbdocs
          message: "Generate dbdocs"
          default_author: github_actions

      - name: Cleanup secrets
        if: always()
        run: rm -rf shared_files/decrypted shared_files/encrypted .vault_password
