# This workflow generates database documentation and ERD files.
#
name: Generate dbdocs

on:
  pull_request:
    paths:
      - .github/workflows/dbdocs.yml
      - db/migrations/bcda
      - db/migrations/bcda_queue

env:
  VAULT_PW: ${{ secrets.VAULT_PW }}

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Decrypt secrets
        run: |
          echo $VAULT_PW > .vault_password
          bash ops/secrets --decrypt
          mv -fv shared_files/encrypted/* shared_files/decrypted/

      - name: Start DB
        run: make reset-db

      - name: Generate DB docs
        run: make dbdocs

      - uses: EndBug/add-and-commit@v9
        with:
          add: dbdocs
          message: "Generate dbdocs"
          default_author: github_actions

      - name: Cleanup secrets
        if: always()
        run: rm -r shared_files/decrypted
