name: opt-out-import dev deploy GF

on:
  push:
    branches:
      - main
    paths:
      - optout/**
      - .github/workflows/opt-out-import-deploy-GF.yml
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Environment you want to deploy to (dev, test, sandbox, prod)'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod

env:
  DEPLOY_ENV: ${{ inputs.deploy_env || 'dev' }}

jobs:
  test:
    environment: ${{ inputs.deploy_env || 'dev' }}
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    defaults:
      run:
        working-directory: bcda
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build opt-out-import zip file
        env:
          CGO_ENABLED: 0
        run: |
          go build -o bin/bootstrap ./lambda/optout/main.go
          zip -j function.zip bin/bootstrap

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/delegatedadmin/developer/${{ vars.AWS_ROLE_TO_ASSUME }}
      - name: Get Bucket
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: | 
            BUCKET=/bcda/${{ env.DEPLOY_ENV }}/bcda-${{ env.DEPLOY_ENV }}-opt-out-import-bucket
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress function.zip \
            s3://$BUCKET/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-${{ env.DEPLOY_ENV }}-opt-out-import \
            --s3-bucket $BUCKET --s3-key function-${{ github.sha }}.zip
