# Tag a new release version, tag it on github, then create a release
name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (or branch name)'
        required: true
        type: string
      ops_release_version:
        description: 'Release version for bcda-ops (or branch name)'
        required: true
        type: string
      next_release_version:
        description: 'Next version (tag or branch name) (OPTIONAL - If not set tag versions will be automatically figured out)'
        type: string
      previous_release_version:
        description: 'Previous version (tag or branch name) (OPTIONAL - If not set tag versions will be automatically figured out)'
        type: string

permissions:
  id-token: write
  contents: write

env:
  GPG_KEY_FILE_NAME: "bcda_ci_github_gpg.key"
  RELEASE_VERSION: ${{ inputs.release_version || 'main' }}
  OPS_RELEASE_VERSION: ${{ inputs.ops_release_version || 'main' }}
  NEXT_RELEASE_VERSION: ${{ inputs.previous_release_version || '' }}
  PREVIOUS_RELEASE_VERSION: ${{ inputs.previous_release_version || '' }}
  RELEASE_GITHUB_USER: carlpartridge
  RELEASE_GITHUB_EMAIL: "carlpartridge@navapbc.com"
  MANUAL_TAG_ARGS: ''

jobs:
  tag_and_release:
    name: Tag and Release
    runs-on: codebuild-bcda-app-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Checkout BCDA
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-app 
          ref: ${{ env.RELEASE_VERSION }}
      - name: Set tags env var
        if: ${{ env.NEXT_RELEASE_VERSION != '' && env.PREVIOUS_RELEASE_VERSION != '' }}
        run: |
          export MANUAL_TAG_ARGS="-t ${{ env.PREVIOUS_RELEASE_VERSION }} ${{ env.NEXT_RELEASE_VERSION }}"
          echo "MANUAL_TAG_ARGS=$MANUAL_TAG_ARGS" >> $GITHUB_ENV
      - name: Get AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            BCDA_GPG_PUB_KEY=/bcda/gpg/pub-key
            OPS_GITHUB_TOKEN=/ci/github/token
      - name: Run release script
        run: |
          echo "${{ env.BCDA_GPG_PUB_KEY }}" > ./${{ env.GPG_KEY_FILE_NAME }}
          GITHUB_REPO_PATH='/CMSgov/bcda-app' GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} GITHUB_USER='${{ env.RELEASE_GITHUB_USER }}' GITHUB_EMAIL='${{ env.RELEASE_GITHUB_EMAIL }}' GITHUB_GPG_KEY_FILE=${{ env.GPG_KEY_FILE_NAME }} bash ops/release.sh ${{ env.MANUAL_TAG_ARGS }}
      - name: Upload release scripts
        uses: actions/upload-artifact@v4
        with:
          name: release-scripts
          path: |
            ./ops/release.sh
            ./ops/github_release.py
      - name: Checkout BCDA-OPS
        uses: actions/checkout@v4
        with:
          repository: CMSgov/bcda-ops
          ref: ${{ env.OPS_RELEASE_VERSION }}
          token: ${{ env.OPS_GITHUB_TOKEN }}
      - name: Download release scripts
        uses: actions/download-artifact@v4
        with:
          name: release-scripts
          path: ops
      - name: Run release for Ops
        run: |
          echo "${{ env.BCDA_GPG_PUB_KEY }}" > ./${{ env.GPG_KEY_FILE_NAME }}
          GITHUB_REPO_PATH='/CMSgov/bcda-ops' GITHUB_ACCESS_TOKEN=${{ env.OPS_GITHUB_TOKEN }} GITHUB_USER='${{ env.RELEASE_GITHUB_USER }}' GITHUB_EMAIL='${{ env.RELEASE_GITHUB_EMAIL }}' GITHUB_GPG_KEY_FILE=${{ env.GPG_KEY_FILE_NAME }} bash ops/release.sh ${{ env.MANUAL_TAG_ARGS }}
      - name: Success Alert
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-deploy
          payload: |
            channel: "C03S23MJFJS"
            attachments:
              - color: good
                text: "SUCCESS: Tag and Release BCDA (${{ env.RELEASE_VERSION }}) and OPS (${{ env.OPS_RELEASE_VERSION }}).  Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"
                mrkdown_in:
                  - text
      - name: Failure Alert
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C03S23MJFJS"
            attachments:
              - color: danger
                text: "FAILURE: Tag and Release BCDA (${{ env.RELEASE_VERSION }}) and OPS (${{ env.OPS_RELEASE_VERSION }}).  Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"
                mrkdown_in:
                  - text


