// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"

	"github.com/pborman/uuid"
)

// Aco represents a row from 'public.acos'.
type Aco struct {
	UUID      uuid.UUID `json:"uuid"`       // uuid
	Name      string    `json:"name"`       // name
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Aco exists in the database.
func (a *Aco) Exists() bool {
	return a._exists
}

// Deleted provides information if the Aco has been deleted from the database.
func (a *Aco) Deleted() bool {
	return a._deleted
}

// Insert inserts the Aco to the database.
func (a *Aco) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.acos (` +
		`uuid, name, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`

	// run query
	XOLog(sqlstr, a.UUID, a.Name, a.CreatedAt, a.UpdatedAt)
	err = db.QueryRow(sqlstr, a.UUID, a.Name, a.CreatedAt, a.UpdatedAt).Scan(&a.UUID)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Aco in the database.
func (a *Aco) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.acos SET (` +
		`name, created_at, updated_at` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE uuid = $4`

	// run query
	XOLog(sqlstr, a.Name, a.CreatedAt, a.UpdatedAt, a.UUID)
	_, err = db.Exec(sqlstr, a.Name, a.CreatedAt, a.UpdatedAt, a.UUID)
	return err
}

// Save saves the Aco to the database.
func (a *Aco) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Upsert performs an upsert for Aco.
//
// NOTE: PostgreSQL 9.5+ only
func (a *Aco) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.acos (` +
		`uuid, name, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (uuid) DO UPDATE SET (` +
		`uuid, name, created_at, updated_at` +
		`) = (` +
		`EXCLUDED.uuid, EXCLUDED.name, EXCLUDED.created_at, EXCLUDED.updated_at` +
		`)`

	// run query
	XOLog(sqlstr, a.UUID, a.Name, a.CreatedAt, a.UpdatedAt)
	_, err = db.Exec(sqlstr, a.UUID, a.Name, a.CreatedAt, a.UpdatedAt)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Delete deletes the Aco from the database.
func (a *Aco) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.acos WHERE uuid = $1`

	// run query
	XOLog(sqlstr, a.UUID)
	_, err = db.Exec(sqlstr, a.UUID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AcoByUUID retrieves a row from 'public.acos' as a Aco.
//
// Generated from index 'acos_pkey'.
func AcoByUUID(db XODB, uuid uuid.UUID) (*Aco, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`uuid, name, created_at, updated_at ` +
		`FROM public.acos ` +
		`WHERE uuid = $1`

	// run query
	XOLog(sqlstr, uuid)
	a := Aco{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, uuid).Scan(&a.UUID, &a.Name, &a.CreatedAt, &a.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
